<?php
// Author: Lisa Wald
// Contact: Brad Aagaard and Dave Wald
// Last modified: Lisa Wald, 2016/08/10
if (!isset($TEMPLATE)) {
  $TITLE = 'Earthquake Processes and Effects';
  $NAVIGATION = true;
    include 'template.inc.php';
}
?>

<h2>East Bay Seismic Experiment</h2>

<figure>
	<img src="images/warrenhall-pano_2x.jpg" alt="Panorama photo of Warren Hall"/>
	<figcaption>
    Before August 2013 Warren Hall towered above the California State University East Bay Campus, with the city of Hayward and San Francisco Bay in the valley below. The Hayward Fault runs along the base of the hills.
  </figcaption>
</figure>

<figure class='right'>
	<a href="images/EBSE-Fault.jpg">
    <img src="images/EBSE-Fault.jpg" alt="Map showing Hayward Fault and instrument sites" title="click to view a larger image">
  </a>
	<figcaption>
    Map showing the deployment of hundreds of seismographs in the city of Hayward that the USGS used to record and observe the implosion of Warren Hall on the campus of California State University East Bay, Hayward.
  </figcaption>
</div>

<p>
  California State University East Bay (CSU-EB) imploded Warren Hall in August of 2013, which was located near the active trace of the Hayward Fault. This implosion provided an excellent opportunity to use a &ldquo;free&rdquo; seismic source that was practically located on the Hayward Fault. 500 to 600 temporary seismographs were deployed in the Hayward area to capture the seismic signal generated by the implosion.
</p>
<p>
  The effort was primarily a collaboration between CSU-EB and the USGS, but other organizations and agencies also conducted additional seismic investigations using the Warren Hall source. From the source, the USGS and CSU-EB recorded the seismic energy as it moved from the source along concentric circles. Because attenuation is generally greater with distance from the source, the concentric circles allowed scientists to measure the same theoretical amplitude (a) in the hard rock of the hills, (b) in the soft rocks/sediments of the valley, (c) within the fault zone, and (d) on the peaks, regardless of the source function. From these measurements, they compared the relative amplification effect of the various geologic terrains. The seismographs were densely spaced so that scientists could also look at the effect of relative amplification within each geologic terrain, which may help to explain why seismic energy can be stronger on one side of a street relative to the other side of the same street.
</p>
<p>
  Along several of the radii extending from Warren Hall, scientists measured seismic velocities (Vp, Vs) in the hills, within the fault zone, and in the valley. These data are very useful in modeling expected ground shaking, and the data can help determine if there are additional faults east and west of the main surface trace. The regional earthquake-monitoring network of seismographs used to locate earthquakes in the Bay Area was turned on before the implosion to record the signal. From these data, scientists can determine how accurately the network located the implosion and provide correction factors, essentially providing a calibration for the network.
</p>

<h2>Photos</h2>

<div class='row'>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-1.jpg">
      <img src="images/tn-ebse-1_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      View of Warren Hall from Harder Rd.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-2.jpg">
      <img src="images/tn-ebse-2_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      Warren Hall pokes up above the hills of Garin/Dry Creek Pioneer Regional Parks.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-3.jpg">
      <img src="images/tn-ebse-3_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      The courtyard above the library is closed off before the implosion.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-4.jpg">
      <img src="images/tn-ebse-4_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      Mark Goldman, USGS Geophysicist, prepares a hole in a volunteer&rsquo;s yard to place a seismometer.
    </figcaption>
    </figure>
  </div>
</div>

<div class='row'>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-5.jpg">
      <img src="images/tn-ebse-5_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      Rufus Catchings, USGS Research Geophysicist, addresses the media at a volunteer&rsquo;s home in the hills above Hayward. The geophones that attach to the seismometers (both a 3-component and a 1-component version) are visible in the photo.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-6.jpg">
      <img src="images/tn-ebse-6_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      Inside the Command Center at CSU-EB where the experiment was conducted.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-7.jpg">
      <img src="images/tn-ebse-7_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      USGS Visiting Scientists Jennifer Dreiling and Marius Isken deploy a seismometer near Warren Hall.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-8.jpg">
      <img src="images/tn-ebse-8_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      Jennifer Dreiling and Marius Isken consult their GPS and field notes.
    </figcaption>
    </figure>
  </div>
</div>

<div class='row'>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-9.jpg">
      <img src="images/tn-ebse-9_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      USGS Visiting Scientist Jennifer Dreiling ensures the geophone is level.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-10.jpg">
      <img src="images/tn-ebse-10_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      Warren Hall memorabilia containing a piece of concrete from the building.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-11.jpg">
      <img src="images/tn-ebse-11_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      The beginning stage of the implosion of Warren Hall on August 17, 2013 at 9am.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-12.jpg">
      <img src="images/tn-ebse-12_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      The aftermath of the implosion, after the building collapsed.
    </figcaption>
    </figure>
  </div>
</div>

<div class='row'>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-13.jpg">
      <img src="images/tn-ebse-13_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      Co-PIs (Principle Investigators) Luther Strayer, CSU-EB and Rufus Catchings, USGS congratulate each other after watching a high-speed video recording of the implosion moments after it occurred.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-14.jpg">
      <img src="images/tn-ebse-14_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      Workers begin cleaning up debris moments after the implosion of Warren Hall.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-15.jpg">
      <img src="images/tn-ebse-15_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      In the days following the implosion, demolition crews work to dismantle the remainders of the structure.
    </figcaption>
    </figure>
  </div>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-16.jpg">
      <img src="images/tn-ebse-16_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      Nighttime shot of the aftermath from the roof of the library.
    </figcaption>
    </figure>
  </div>
</div>

<div class='row'>
  <div class='column one-of-four'>
    <figure>
      <a href="images/ebse-17.jpg">
      <img src="images/tn-ebse-17_2x.jpg" alt="thumbnail photo" title="click to view a larger image">
    </a>
    <figcaption>
      After the implostion, several stories of the western facade still remain.
    </figcaption>
    </figure>
  </div>
</div>

<figure>
  <figcaption>
    Photos by <a href="mailto:shaefner@usgs.gov">Scott Haefner</a>
    </figcaption>
  </figure>

<h2>Data</h2>
<p>
  <a href="https://www.sciencebase.gov/catalog/item/54860802e4b02acb4f0c7ea6">2013 East Bay Seismic Experiment (EBSE) &mdash; Implosion Data, Hayward, California</a>
</p>

<h2>Example of amplification of seismic waves in fault zones</h2>

<figure>
  <img src="images/SAF-Amplification_2x.jpg">
	<figcaption>
    Example of amplification of seismic waves in fault zones.<br/>
    (a) Plot of peak ground velocity (amplitude) as a function of distance across the San Andreas Fault. Note the high amplitudes centered over the San Andreas Fault.<br/>
    (b) Cross section of seismic velocities across the San Andreas Fault. The main trace of the San Andreas Fault that ruptured in 1906 is located at about meter 31 of the seismic profile (see red arrow). Two other minor faults are shown at meters 4 and 41. Note the very low seismic velocities of material within the main fault zone relative to the areas to either side. Many other fault zones have shown similar amplification.
  </figcaption>
</figure>

<h2>See Also</h2>
<ul>
	<li><a href="http://www.usgs.gov/newsroom/article.asp?ID=3623">USGS Press Release: Opportunity to Study Hayward Fault Comes with Cal State East Bay&rsquo;s Planned Building Demolition</a></li>
	<li><a href="http://www20.csueastbay.edu/news/2013/01/WarrenHallDemo-013013.html">California State University East Bay: CSU trustees earmark $50M to remove, replace Warren Hall</a></li>
	<li><a href="http://www.livescience.com/37617-building-demolition-hayward-fault-study.html">LiveScience: Building Explosion Will Shed Light on Nearby Earthquake Fault</a></li>
	<li><a href="http://storify.com/stanfordbabs/opportunity-to-study-hayward-fault-comes-with-cal">Barbara Wilcox&rsquo;s Storify feed</a></li>
</ul>
