<?php
// Author: Lisa Wald
// Contact: Jim Dewey
  if (!isset($TEMPLATE)) {
    $TITLE = 'Routine United States Mining Seismicity';
    $NAVIGATION = true;
    $CONTACT = 'dewey@usgs.gov';
    include 'template.inc.php';
  }
?>

<h2>Goal and Scope of the Catalog</h2>
<p>
  "Routine Mining Seismicity in the United States" is an effort
  to catalog the larger of the many seismic events in the U.S. that are caused
  by mineral-resource industries in the course of their normal operations.
  Most of these seismic events are planned explosions; some are planned roof
  collapses associated with longwall mining.
</p>

<p>
  The USGS/National Earthquake Information Center (USGS/NEIC) is responsible
  for monitoring the occurrence of earthquakes within the United States. The
  USGS/NEIC uses seismographic data from the U.S. National Seismographic Network
  (USNSN) and many other cooperating networks in the United States and throughout
  the world. USGS/NEIC personnel attempt to obtain estimates of the locations
  and magnitudes of earthquakes that are large enough to be felt in the U.S.
  For much of the U.S., earthquakes of magnitude 2.5 or larger are located
  and cataloged by the USGS/NEIC. In other parts of the U.S., the threshold
  of earthquakes that can be located and cataloged is higher, due either to
  the remoteness of those regions from seismographs or due to earthquake levels
  that are so high that a higher threshold of cataloging still reveals the
  important features of local seismicity. Within the conterminous U.S., the
  level of completeness for earthquake location by the USGS/NEIC is probably
  in the magnitude 3.0-3.5 range.
</p>

<p>
  Intentionally detonated mine or quarry explosions and planned roof collapses
  produce seismic signals that are broadly similar to the seismic signals
  produced by earthquakes, and the process of monitoring natural seismicity
  has therefore involved identifying these routinely occurring mining seismic
  events and ensuring that they are not misidentified as natural earthquakes.
  The USGS/NEIC has historically dealt with routine mining seismic events
  by identifying them at an early stage of analysis and removing them from
  further analysis procedures, so that full effort could be devoted to earthquakes
  that might reflect seismically hazardous situations. Many of the U.S. regional
  networks that cooperate with the USGS/NEIC have had the same policy. Now,
  however, with the U.S. being a signatoree of the
  <a href="http://www.ctbto.org/the-treaty/">Comprehensive Nuclear-Test-Ban Treaty (CTBT)</a>,
  there is an interest in maintaining
  publically-accessible catalogs of mine seismicity as a
  <a href="http://www.ctbto.org/the-treaty/treaty-text/">CTBT confidence-building measure</a>.
  The possible impact of mine seismicity
  on the CTBT is reviewed in a document published by the Department of Energy
  (Mine Seismicity and the Comprehensive Nuclear-Test_Ban Treaty, Report of
  a Working Group from Government, Industry, and National Laboratories, Department
  of Energy Report LA-UR-99-384).
</p>

<p>
  The epicenters listed in the &quot;Routine Mining Seismicity in the United
  States&quot; catalogs are calculated from the arrival times of seismic phases
  recorded on seismographs that record at the USGS/NEIC. The epicenters are
  therefore approximate, with accuracies that depend on the location of the
  mines with respect to the recording seismographs (see
  <b><a href="definitions.php">Explanation of Catalog Listings</a></b>
  and
  <b><a href="sources.php">Mining Seismicity Source Regions</a></b>
  for discussions of epicentral accuracies).
</p>

<p>
  The magnitudes assigned to the events in the &quot;Routine Mining Seismicity
  in the United States&quot; catalogs are calculated from the amplitudes of
  local and regional seismic phases. The magnitudes assigned to events that
  occur east of the Rocky Mountains are mbLg magnitudes and should be approximately
  equal to the mb magnitudes that would be assigned to those events if P-wave
  readings were available from teleseismic distances. The magnitudes assigned
  to events that occur in the western U.S. are ML magnitudes; a preliminary
  analysis suggests that they tend to be somewhat smaller than the mb magnitudes
  that would be assigned if P-wave readings were available from teleseismic
  distances. Other studies (e.g., Anandakrishnan and others, 1997; Carr and
  Garbin, 1998; Khalturin and others, 1998) indicate that neither the mbLg
  nor ML magnitude provides an accurate measure of the total charge size of
  a given explosion: the explosions are ripple fired, and the amplitudes of
  short-period seismic waves generated by a multiple-charge explosion are
  greatly influenced by the sizes, spacing and timing of individual charges.
</p>

<p>
  In any given region, the magnitude level for essentially complete detection
  and location of mining associated seismicity will occur at, or slightly
  above, the magnitude level at which earthquakes are essentially completely
  detected and located. There are several factors that may make it more difficult
  to detect/locate mine seismicity than to detect/locate earthquakes.
</p>

<ul>
  <li>A. P-waves from mine-explosions tend to be more emersive than P-wave
  from earthquakes, making automatic P-wave detection more difficult for
  explosion signals than for earthquake signals.</li>
  <li>B. In many mining districts, numerous explosions occur during working
  hours, making more difficult the automatic association of specific arrival-times
  with specific epicenters/origin times than is the case with earthquakes.</li>
  <li>C. Felt reports are important for detection/location of small earthquakes
  in regions that are not well-instrumented with seismographs, but mine explosions
  and planned longwall collapses tend not to be reported as felt.</li>
</ul>

<p>
  The above considerations suggest that mine explosions and roof collapses
  in the magnitude (ML or mbLg) 3.0 - 3.5 range, or slightly larger, could
  occur in some parts of the conterminous U.S. and escape detection/location.
  In fact, in <b><a href="sources.php">Mining Seismicity Source Regions</a></b> we
  note a case of a magnitude 3.4 explosion in Minnesota that could not have
  been located solely with data recorded at the USGS/NEIC, and we note a case
  of a well-recorded mine explosion in West Virginia, magnitude 3.4, that
  was not detected by the USGS/NEIC automatic event-detection algorithm, apparently
  because the algorithm attempted to recognize an event in the signals of
  more than one explosion. We also note that the number of mining-associated
  seismic events located in West Virginia and vicinity dropped dramatically
  in 1999 -- 2000 compared with 1997; this reduction is probably a consequence
  of a temporary reduction in the number of stations from this region that
  are recording at the USGS/NEIC. Stations are still being added to the network
  that records at the USGS/NEIC; for some regions, the new stations will dramatically
  lower the magnitude level at which explosions are completely detected and
  located. It must be emphasized, however, that the completeness and accuracy
  of the catalog in many regions is strongly dependent on the health of local
  seismograph networks with which the USGS/NEIC is cooperating. The future
  quality of the catalog will degrade for regions in which local networks
  are cut back due to lack of funding.
</p>

<p>
  At present, our bulletins, catalogs, and maps cover only the 48 conterminous
  states of the United States.
  <b><a href="sources.php">Mining Seismicity Source Regions</a></b>
  lists one mining region in Alaska that has been recognized
  to detonate explosions that are recorded on regional seismographic stations.
</p>

<h3>Notes for Specific Time Periods</h3>
<ul>
  <li>
    <h4>May&ndash;September, 1997</h4>
    <p>
      The catalog lists epicenters for all suspected mining seismic events for
      which we had sufficient data to obtain a stable location. These epicenters
      represent only a small fraction of the total number of mining seismic events
      detected by seismographs reporting to the USGS/NEIC, because many seismic
      events are only recorded by one or two seismographs.
    </p>
  </li>
  <li>
    <h4>October&ndash;November, 1997</h4>
    <p>
      We focused cataloging efforts on events for
      which computed magnitudes were 2.0 or higher and for which stable calculations
      of the epicenters could be achieved in several computation attempts.
    </p>
  </li>
  <li>
    <h4>December, 1997&ndash;April, 1998</h4>
    <p>
      We suspended the cataloging of mine seismicity except for a few events of special interest.
    </p>
  </li>
  <li>
    <h4>May&ndash;July, 1998</h4>
    <p>
      This was a training period for a new analyst; cataloged events
      were selected for their usefulness in training, rather than according to
      a magnitude criterion.
    </p>
  </li>
  <li>
    <h4>August, 1998&ndash;June, 1999, and from October, 1999&ndash;present</h4>
    <p>
      Mining-associated seismic events having magnitude (ML, USGS) 2.5 or greater
      in the western U.S., or having magnitude (mbLg, USGS) 3.0 or greater in
      the eastern U.S., are listed if they are automatically detected and located
      by the USGS/NEIC near-real time system and if, after examination of the
      data by the analyst, a stable epicenter can be computed. In addition, smaller
      events are catalogued if, (1), they provide information on the characteristics
      of a region's mine-associated seismicity that cannot be obtained with the
      larger events or, (2), their epicenters have been reliably determined in
      the course of searching for larger events.
    </p>
  </li>
  <li>
    <h4>July&ndash;September, 1999</h4>
    <p>
      We listed only suspected mining-associated
      events that were reported in the Reviewed Event Bulletin (REB) of the Prototype
      International Data Center (PIDC).
    </p>
  </li>
  <li>
    <h4>October, 2002&ndash;present</h4>
    <p>
      We list only suspected mining-associated events
      that were reported in the Reviewed Event Bulletin (REB) of the International
      Data Center (IDC).
    </p>
  </li>
</ul>

<h3>References</h3>
<ul class='referencelist'>
  <li>
    Anandakrishnan, S., Taylor, S.R., and Stump, B.W., 1997, Quantification and characterization of reigonal seismic signals from cast blasting in mines: a linear elastic model: Geophysical Journal International, v. 131, p. 45-60.
  </li>
  <li>
    Carr, D.B., and Garbin, H.D., 1998, Discriminating ripple-fired explosions with high-frequency (&gt; 16Hz) data: Bulletin of the Seismological Society of America, v. 88, p. 963-972.
  </li>
  <li>
    Khalturin, V.I., Rautian, T.G., and Richards, P.G., 1998, The seismic signal strength of chemical explosions: Bulletin of the Seismological Society of America, v. 88, p. 1511-1524.
  </li>
</ul>
