<?php
if ( ! isset( $TEMPLATE ) ) {

  $TITLE = "Comments on 1906 Ground Motion Movies";
  $HEAD ="";
  $FOOT = "";

  include "template.inc.php";
} ?>

    <h2>Color Scheme in Movie</h2>
          <p>
  The movies show the propagation of seismic waves away
  from the epicenter, which lies 2 miles offshore from
  San Francisco.  The residual
  colors</a> indicate the peak shaking intensity experienced at
  locations up to the time, in seconds, indicated near the
  top center of the movie.  The current intensity, at
  the time shown on the view, is indicated by <a
  href="../colors.php">shading of the colors</a>.
          </p>

          <h2>Spatial Variations in Shaking Intensity</h2>

          <p>
  Note that the rupture front simultaneously propagates
  to the north and south along the San Andreas fault
  away from the epicenter.  The character of the shaking
  at any location is influenced by the amount of slip on
  nearby sections of the fault, properties of the
  geologic materials that the waves passed through to
  reach the location, and especially the local ground
  conditions at the location.
          </p>
          <p>
  Sites on bedrock are often less susceptible to strong
  shaking than sites located on unconsolidated
  sediments.  In particular, thick accumulations of
  deposits in sedimentary basins tend to amplify
  shaking, not unlike a bowl of jello.  For example,
  Santa Rosa experienced heavy damage in 1906 and it can
  be seen in the simulation that high intensities of
  shaking are predicted by the computer model.
  These high intensities in the simulations result from
  sedimentary deposits under Santa Rosa, which were included in the
  the 3-D Geologic Map used as input to the model.
  Much of the character in the
  final shaking intensities offshore can also be
  attributed to the presence of offshore sedimentary
  basins.
          </p>

        <h2>1906 Earthquake Parameters</h2>
   <ul>
    <li>Magnitude: Mw 7.8-7.9</li>
    <li>Hypocenter: 122.55 W, 37.75 N, 6 miles (10 km) depth</li>
    <li>Rupture length (total): 300 miles (480 km)</li>
    <li>Rupture length (north): 205 miles (330 km)</li>
    <li>Rupture length (south): 93 miles (150 km)</li>
    <li>Rupture duration (north): 90 s</li>
    <li>Rupture duration (south): 54 s</li>
    <li>Average offset along the fault: 10 ft (3 m)</li>
   </ul>

        <h2>1906 Wave Propagation</h2>

   <ul>
    <li>Average S wave speed: 8000 mph (3.6 km/s)</li>
    <li>Average P wave speed: 14000 mph (6.2 km/s)</li>
    <li>It takes less than 30 seconds for strong shaking to envelope the entire San Francisco Bay area.</li>
   </ul>

   <table class="tabular">
     <tr><th>City</th><th>Shaking begins</th><th>Strong shaking begins</th><th>Distance from epicenter</th><th>Max ground displacement</th></tr>
     <tr><td>San Francisco (Ocean Beach)</td><td>1.7 s</td><td>2.4 s</td><td>2 miles (3 km)</td><td>~2 ft</td></tr>
     <tr><td>San Francisco (City Hall)</td><td>2.6 s</td><td>3.4 s</td><td>7 miles (12 km)</td><td>~2 ft</td></tr>
     <tr><td>Oakland</td><td>4.9 s</td><td>6.2 s</td><td>16 miles (25 km)</td><td>~2 ft</td></tr>
     <tr><td>San Jose</td><td>13.0 s</td><td>20.6 s</td><td>46 miles (74 km)</td><td>~2 ft</td></tr>
     <tr><td>Santa Rosa</td><td>13.7 s</td><td>16.9 s</td><td>48 miles (78 km)</td><td>~2 ft</td></tr>
   </table>

        <h2>Movies Tracking Fault Rupture</h2>
          <p>
            These movies follow the fault rupture by flying along the
            fault. One movie follows the rupture south while the other
            follows the first 28 seconds of rupture to the north. The
            seismic waves seen in the map view movies above are
            generated by slip on the fault.  Note that the fault is
            deformed horizontally as the rupture travels up the fault,
            leaving in its wake an offset of 20-30 feet in some places.
          </p>
          <p>
            <ul>
             <li>Movie following rupture south:
               <a href="https://escweb.wr.usgs.gov/content/education/shakingsimulations/1906/sf1906flysouth_hires.mp4">normal resolution</a> (960x540, 37 MB)
             </li>
             <li>Movie following rupture north:
               <a href="https://escweb.wr.usgs.gov/content/education/shakingsimulations/1906/sf1906flynorth_hires.mp4">normal resolution</a> (960x540, 21 MB)
             </li>
            </ul>
          </p>

  <h2>1906 Tsunami</h2>
          <p>
  A small, 4 inch high, <a
  href="http://walrus.wr.usgs.gov/tsunami/1906.html">tsunami
  was generated by the 1906</a> earthquake and was
  measured at the Presidio tidal gauge.  The tsunami
  rapidly decreased in size as it entered San Francisco
  Bay. Modeling of this tsunami provided useful
  information regarding the location of the epicenter
  offshore and the nature of the initial rupture
  process.
          </p>
          <p id="back">&laquo; <a href="./">Back</a></p>
