<?php
      //	Author:	Tiffany Kalin
      //	Contact:
      //	Last	modified:	10/12/2016
      if	(!isset($TEMPLATE))	{
      $TITLE	=	'The Early History of Seismometry (to 1900)';
      $NAVIGATION	= true;
      include	'template.inc.php';
      }
?>
<h2>by<br>James Dewey and Perry Byerly</h2>

<blockquote>
	<h3>The "Seismometer" of James Forbes</h3>

	<p>
		The interest in seismic instruments generated by the Calabrian
		earthquakes was not sustained in succeeding years. In 1839, however,
		a series of small earthquakes began near Comrie, in Perthshire,
		Scotland. Scores of shocks were felt over a period of several
		years. A direct result of the Comrie earthquakes was the establishment
		of a Special Committee of the British Association for the
		Advancement of Science, the purpose of
		the committee being to obtain "instruments and registers
		to record shocks in Great Britain" (Milne, 1842).
	</p>
	<p>
		The most significant instrument resulting from the
		committee's work was an inverted-pendulum "seismometer",
		designed by James Forbes (Forbes, 1844).
		The seismometer is shown in Figure 2. It consisted of a
		vertical metal rod having a mass <i>C</i>
		moveable upon it. The rod was supported on a vertical
		cylindrical steel wire. The wire
		could be made more or less stiff by pinching
		it at a greater or lesser height by means of
		a screw <i>S</i>. By adjusting the stiffness of the wire,
		or the height of the ball, the free period
		of the pendulum might be altered. A pencil <i>L</i>
		placed on the prolongation of the metal rod
		wrote a record on a stationary, paper-lined, spherical dome <i>I</i>.
		By placing the pencil sufficiently far above the mass, a
		magnification of the motion of the mass
		by a factor of two or three could be obtained.
	</p>
	<figure class="left" style="max-width:257px">
		<img src="figures/fig_02.gif"/>
		<figcaption>
			Figure 2. Forbes' seismometer (after Forbes, 1844).
			The screws <i>E</i>, acting on the support <i>D</i>,
			are used to help set the pendulum in an upright position.
		</figcaption>
	</figure>
	<p>
		Forbes used the inverted pendulum, mounted on a stiff wire, to
		provide a sensing element in weakly-stable equilibrium, without
		having to use a very long common
		pendulum. An upright inverted pendulum, by itself, is
		in unstable equilibrium. A
		slight motion topples it over. When the inverted
		pendulum is mounted on a suitably stiff wire, the
		apparatus may be rendered stable, so that the inverted
		pendulum returns to an upright position after having been
		disturbed. Such a combination had been used
		already by a Mr. Hardy for the purpose of detecting
		vibrations set up in a clock
		frame by the beating of the clock (Kater, 1818).
	</p>
	<p>
		Forbes was probably the first to attempt explicitly to give
		a seismological instrument a "long" period.
		<font size=-1>
		[Forbes speaks of requiring, for earthquake recording, a
		common pendulum, ten or twenty
		feet long, which would have a period of four or five seconds
		(Forbes, 1844, p. 219).
		Later, in a discussion of the size of his seismometer, he
		states that the sensibility of
		seismometers of different size should be
		the same - "say one second" (Forbes, 1844, p. 221).
		We suspect, however, that he hoped for a period
		nearer five seconds than one second,
		since his seismometer offered no advantage in
		compactness over a common pendulum
		with a one-second period. We have found no indication
		of the period actually obtained with the instrument.]
		</font>
		He was also the first to try to avoid the
		clumsiness of a long common pendulum in obtaining long periods.
		As we shall see, his method of
		approaching neutral equilibrium was similar to that used
		by Wiechert in 1900. Forbes desired a
		long period in order that the pendulum remain stationary
		as the Earth moved beneath it. He clearly wanted to measure
		ground displacement in an earthquake. However, he
		considered only the effect on his instrument of an "earthquake"
		consisting of a single, horizontal displacement of uniform
		velocity, beginning and ending suddenly. For this reason,
		we can't be sure if Forbes knew that a long-period pendulum
		would function as a displacement meter for very-short-period
		oscillations of the ground. For the type of
		motion he considered, Forbes expected his seismometer to show
		a straight line, corresponding to the sudden displacement
		of the Earth, which would be easily distinguished
		from the ellipsoidal traces caused by the pendulum
		oscillating about its new equilibrium position.
	</p>
	<p>
		A mathematical theory of the instrument accompanies its
		description (Forbes, 1844).
		Forbes was the first to describe mathematically the behavior
		of a seismic instrument in
		an "earthquake". The assumed earthquake, again, is a single motion
		of uniform velocity, starting and stopping abruptly.
	</p>
	<p>
		Six of the inverted-pendulum seismometers were set up
		at Comrie (Milne, 1842, 1843). One was thirty-nine inches long
		and another was ten feet long. The lengths of the
		remaining four were not noted. Neither were the periods of the
		instruments noted. They gave disappointing performances. In
		one year, for example, the seismometers recorded
		only three of sixty earthquakes felt at Comrie (Milne, 1843).
		The nature of the records is difficult to decipher from the
		descriptions given by the investigators, who mention
		the indicating pencil being displaced by the quake, but don't
		mention any records being written by it. They conclude that the
		motion in the recorded earthquakes consisted of a sudden
		movement of the ground, with a maximum displacement
		of one half of an inch horizontally (Milne, 1842, 1843).
	</p>
	<p>
		Friction between the writing pencil and the recording surface
		must take some of the blame for the disappointing results
		given by the seismometer. Forbes was aware of the
		problem of friction. He attempted to overcome it by
		using a heavy mass, but he does
		not seem to have been successful. We will see that friction
		would severely limit the
		sensitivity of many later seismographs which had
		mechanical registration.
	</p>
	<p>
		Common pendulums and an instrument for measuring vertical
		motion were also used at Comrie. The vertical motion
		seismoscope consisted of a horizontal metal bar, loaded
		with a weight at one end, and fastened to the wall with a
		flat spring. In an earthquake, the weight was expected to
		lag behind the ground motion and move a light straw
		to indicate the extent of vertical motion. The vertical-motion
		instrument functioned on several occasions, indicating
		vertical "displacements" as great as
		half an inch.
	</p>
	<p>
		The earthquakes at Comrie diminished in number, and after several
		years the committee on earthquake instruments was allowed
		to dissolve.
	</p>

	<p>
		<small>
  		From the <i>Bulletin of the Seismological Society of America</i>.
  		Vol. 59, No. 1, pp. 183-227. February, 1969.
		</small>
	</p>
</blockquote>

<!-- NAVIGATION at bottom for ARTICLE -->
<p>
  <a class='prev' href="part04.php">
    <span class='material-icons prev'>&#xe5c4;</span>
    <strong>PREV</strong>
  </a>
  <a class='next' href="part06.php">
    <strong>NEXT</strong>
  <span class='material-icons next'>&#xe5c8;</span>
  </a>
</p>
