<?php

if (!isset($TEMPLATE)) {
  $TITLE = 'Body waves inside the earth';
  $HEAD = '';
  $NAVIGATION  = true;

  include 'template.inc.php';
}

?>


<p>Two kinds of waves are generated by earthquakes and travel through solid rock:</p>

<img src="images/wave.gif" alt="Diagram illustrating P and S waves."  />

<p>In P or compressional waves, the vibration of the rock is in the direction of propagation. P waves travel fastest and are the first to arrive from the earthquake. In S or shear waves, rock oscillates perpendicular to the direction of wave propagation. In rock, S waves generally travel about 60% the speed of P waves, and the S wave always arrives after the P wave. For example, sound waves are P waves at a high enough frequency to hear with your ear. An example of an S wave is wiggling or shaking a rope which is tied down at one or both ends.</p>

<img src="images/rays.gif" alt="Body waves inside the earth seen as arrivals on seismograms." />

<p>Both P and S waves travel outward from an earthquake focus inside the
earth. The waves are often seen as separate arrivals recorded on seismographs
at large distances from the earthquake. The direct P wave arrives first
because its path is through the higher speed, dense rocks deeper in the
earth. The PP (one bounce) and PPP (two bounces) waves travel more slowly
than the direct P because they pass through shallower, lower velocity
rocks. The different S waves arrive after the P waves.</p>

<p> The slowest (and latest to arrive on seismograms) are surface waves,
such as the L wave. L waves are named for the Cambridge mathematician
A.E.H. Love who first described them. The surface waves are generally
the largest recorded from an earthquake. Body waves in the earth's interior
lose their amplitude rapidly as they get farther from the earthquake because
they spread out inside the volume of the earth. Surface waves, however,
spread out more slowly and only on the earth's surface. The energy from
surface waves is confined to a smaller volume at the surface and the wave
amplitude to carry that energy is therefore larger than body waves.</p>

<p>A reference for further reading is:</p>

<p><em>Inside the Earth, Evidence from Earthquakes; </em>by Bruce A. Bolt,
W.H. Freeman & Co., San Francisco, first published 1982.</p>
