<?php
	// Webpage contact - Lisa Wald
	// Content contact/SME - Peter Haeussler
	// Created June 2015
	// Last updated 06/23/2015

	$TITLE = "The &quot;Snow Plow Theory&quot;* of Early-Arriving Tsunamis";

	$STYLESHEETS = "/research/style.css"; 
	// $SCRIPTS = "/js/ibox.js";
	
	include_once $_SERVER['DOCUMENT_ROOT'] . "/template/template.inc.php";
?>

<p>* completely contrived term by this author, not a scientific term or theory</p>

<h2>Additional Resources</h2>

<ul class="references">
  <li>
  <a href="http://earthquake.usgs.gov/earthquakes/events/alaska1964/">
  The Great Alaska Earthquake and Tsunami of March 27, 1964</a>
  </li>
  <li>
  <a href="https://youtu.be/jvl-4IWjHXo">
  Magnitude 9.2: The 1964 Great Alaska Earthquake</a>
  </li>
  <li>
  <a href="http://www.iris.edu/hq/programs/education_and_outreach/animations/33
">
  Tsunamis Generated by Megathrust Earthquakes</a> (IRIS)
  </li>
  <li>
  <a href="http://shearsensibility.blogspot.com/2008/12/thrust-belt-in-my-driveway.html
">
  The Thrust Belt in My Driveway</a> (blog page by a geology professor)
  </li>
  <li>
  <a href="http://beachsafe.org.au/tsunami/ema/pages/04b_landslides.html">
  Undersea Landslide-generated Tsunami Animation</a> (Australian Beachsafe website)
  </li>
  <li>
  <a href="http://beachsafe.org.au/tsunami/ema/pages/04a_earthquake.html
">
  Subduction Zone Rupture-generated Tsunami</a> (Australian Beachsafe website)
  </li>
  <li>
  <a href="http://pubs.er.usgs.gov/publication/cir491">
  Alaska's Good Friday earthquake, March 27, 1964, a preliminary geologic evaluation</a>
  </li>
  <li><a href="http://www.earthscope.org/science/geo-events/m9.1-indonesia-earthquake-2004">M9.1 Indonesia Earthquake 2004</a> (EarthScope)
  </li>
</ul>
