<?php
  // Author: Lisa Wald
  // Contact: Justin Rubenstein
  // Last modified: Lisa Wald, 2016/08/22
    if (!isset($TEMPLATE)) {
      $TITLE = 'Induced Earthquakes';
      $NAVIGATION = true;
      $HEAD = '
        <link rel="stylesheet" href="index.css"/>
      ';
        include 'template.inc.php';
    }
?>

<figure class='right'>
	<img src="images/installation.jpg" alt="Photo of Bryant Platt"/>
	<figcaption>
    Bryant Platt digs a hole to install seismometers at a home in southern Kansas.  Seismometers are in the foreground.
  </figcaption>
</figure>

<h2>Observational Studies</h2>

<p>
  In response to sudden changes in seismicity that are potentially induced by human activity, the USGS may deploy temporary seismic stations to better understand the earthquakes. These deployments typically consist of 2-15 seismometers placed in the immediate vicinity of the seismicity.
</p>
<p>
  Temporary seismic stations allow us to accurately pinpoint the location of the seismicity including small earthquakes that are not recorded by permanent US seismic networks. With the high-quality data from temporary seismic stations we are able to precisely locate the seismicity, identify activated fault structures, determine the faulting style of the earthquakes, and monitor for migration of the seismicity with time. All of these characteristics help us understand if the earthquakes are induced and the physical processes causing them.
</p>
<p>
  The catalog of earthquakes generated by the temporary seismic stations provides key data for basic research to understand the mechanics of induced earthquakes. Scientists commonly use <a href="modeling.php">computer models</a> to simulate the physical processes believed to be responsible for inducing earthquakes to better understand why they occur and how they might be prevented. The USGS also uses the observations from these seismic networks to inform forecasts of <a href="hazards.php">earthquake hazard due to induced earthquakes</a>.
</p>
<p>
  As part of these observational studies, the USGS works closely with scientists at local universities, state geological surveys, state regulatory agencies, and other scientific institutions. Working with these partners is critical for our work. They bring local knowledge and understanding of these areas, and complement the technical capabilities of the USGS. Local partners frequently assist or lead our deployments of temporary seismic stations, as they are often able to deploy the instrumentation more quickly than scientists from the USGS offices in California, Colorado, and New Mexico. Local homeowners are also critical for our studies, as they often host our seismic monitoring equipment.
</p>

<figure>
	<img src="images/map.jpg" alt="Map of Central U.S."/>
	<figcaption>
    Map of current USGS temporary seismic deployments to monitor potentially induced earthquakes.
  </figcaption>
</figure>
