<?php
      //	Author:	Tiffany Kalin
      //	Contact:
      //	Last	modified:	1/11/2017
      if	(!isset($TEMPLATE))	{
      $TITLE	=	'1964 Alaska Earthquake Seismograms';
      $NAVIGATION	= true;
      include	'template.inc.php';
      }
?>

<p>
	<h2><font color="0000FF">Short Period Seismogram from the 1964 Alaska Earthquake</font></h2>
</p>
<p>
	Station Code: DAL<br />
	Southern Methodist University<br />
	Dallas, Texas<br />
	Vertical-Component Benioff Seismometer<br />
	Magnification: 1,500<br />
	Start Time of Record: March 27, 1964, 17 hours, 39 minutes UTC
</p>
<p>
	<img src="img/1964_03_28_spw.gif" alt="Seismogram" longdesc="Seismogram" />
</p>
<p>
	This is a 24-hour long seismic record.<br />
	Time progress left to right and from top to bottom, just like text on a printed page.<br />
	Each line is 15 minutes long.  <br />
	The hour marks are visible as a vertical stripe parallel to the
	left edge of the record.
</p>
<hr />
<p>
	<h2><font color="0000FF">Long Period Seismogram from the 1964 Alaska Earthquake</font></h2>
</p>
<p>
	Station Code: DAL<br />
	Southern Methodist University<br />
	Dallas, Texas<br />
	Vertical-Component Sprengnether Seismometer<br />
	Magnification: 25,000<br />
	Start Time of Record: March 27, 1964, 17 hours, 39 minutes UTC
</p>
<p>
	<img src="img/1964_03_28_lpw.gif" alt="Seismogram" longdesc="Seismogram" />
</p>
<p>
	Time progress left to right and from top to bottom, just like text on a printed page.<br />
	Each line is 30 minutes long.<br />
	The minute marks are visible as diagonal stripes on the upper half of the record.
</p>
<hr />
<p>
	The original records were made photographically with a light beam
	focused on a piece of photographic paper.  When waves from the
	1964 earthquake arrived the beam began moving back and forth so
	quickly that the photographic paper did not receive enough light
	to register the position of the trace.  This situation continued
	for many hours following the earthquake, which is why the records
	above have a white band at the center.
</p>
<hr />
<p>
	<h2><font color="0000FF">Long Period Seismogram from the 1964 Alaska Earthquake</font></h2>
</p>
<p>
	Station Code: COL
	<br />
	College, Alaska
	<br />
	Sprengnether seismometers
</p>
<p>
	<img src="img/1964_03_28_col_lp.jpg" alt="Seismogram" longdesc="Seismogram" />
	<br />
	<i>Photograph by Jack Townshend, 2003.</i>
	</p>
	<p>
</p>
<p>
	The seismograms reproduced above recorded east-west ground motion via a long-period
	Sprengnether seismometers and a sensitive galvanometer. Time progresses from left to right and
	from top to bottom, just like text on a printed page. Each line is 60 minutes long with a short
	vertical line identifying each minute. Component, magnification, date, and the beginning and
	ending time are noted on the left side of the each seismogram.
</p>
<p>
	The original record was made photographically with a light beam
	focused on a piece of photographic paper. When waves from the
	1964 earthquake arrived the beam began moving back and forth so
	quickly that the photographic paper did not receive enough light
	to register the position of the trace. This situation continued
	for many hours following the earthquake, which is why the record
	from March 27 shows little after the arrival of the P-wave at the
	red arrow.
</p>
<p>
	Eventually the electrical current generated by the motion of the seismometer exceeded the
	capacity of the galvanometer and the galvanometer mirror reflecting the light beam became stuck
	in an extreme position until it was readjusted early the next day.
</p>
