<?php
      //	Author:	Tiffany Kalin
			// Webpage contact - Lisa Wald
			// Content contact/SME - Art Frankel, afrankel@usgs.gov
      //	Last	modified: 11/21/2016
      if	(!isset($TEMPLATE))	{
      $TITLE	=	'Animation of Ground Motions Produced by the Implosion of the Kingdome';
      $NAVIGATION	= true;
      include	'template.inc.php';
      }
?>
<p>
  <video width="563" height="458" controls>
    <source src="media/kingdome.mp4" type="video/mp4">
  Your browser does not support the video tag.
  </video>
  <!--<video src="media/kingdome.mp4" poster="images/kingdome.gif" alt="Click to view Kingdome animation" width="563" height="458" controls></video>-->
</p>

<p>
	This computer animation of the ground motions generated by the Kingdome Implosion (March, 2000) was created using the recordings of about 150 digital seismographs deployed in the Seattle area. For the animation, the vertical-component seismograms were used from the Texan seismographs. The seismograms were bandpass filtered between 1 and 2 Hz and then enveloped. At each time step, the logarithm of the envelope amplitude was spatially-interpolated between the sites to form a map of the ground motion envelope for that time.
</p>
<p>
	This animation is derived from the actual ground motions from the Kingdome Implosion; it is not from a simulation.
</p>
<p>
	The animation shows 60 sec of observed ground motions. The circles indicate the locations of the seismographs used to make the animation. The red line indicates the coastline. The beginning of the animation shows the high ground motions around the Kingdome during the implosion. The red colors correspond to the highest ground motions. Gradually the ground motion spreads out from the Kingdome, as seen by the green wavefield. It takes about 25 sec for the largest ground motions to reach the extreme north and south edges of the map, about 14 km from the Kingdome. These ground motions are probably dominated by surface waves.
</p>
<p>
	Strong pulses of ground motion can be seen propagating through the artificial fill in Harbor Island and the soft soils around the Duwamish Waterway. Another strong pulse of motion is observed in the area northeast of the Kingdome, in the Madrona and Madison Park areas and near the western end of the 520 bridge. We do not yet know if these high ground motions are caused by local soil conditions or are due to some focusing effect from the shallow sedimentary units.
</p>
<p>
	We can see that high ground motions persist in Harbor Island and near the Duwamish Waterway until the end of the animation. This documents the amplification and prolongation of ground shaking at these soft-soil sites.
</p>

<p>
	Scientific Staff: Art Frankel, Tom Brocher, Tom Pratt, and Craig Weaver
</p>

<h2 class="referencelist">References</h2>
<ul>
	<li>
		Urban Seismic Experiments Investigate Seattle Fault and Basin, EOS, v. 81, no. 46, Nov. 14, 2000.
	</li>
</ul>
