<?php
      //	Author:	Tiffany Kalin
			// Webpage contact - Lisa Wald
			// Content contact/SME - Art Frankel, afrankel@usgs.gov
      //	Last	modified:	11/21/2016
      if	(!isset($TEMPLATE))	{
      $TITLE	=	'Animation of ground motions recorded by the San Jose Dense Seismic Array from the M5.6 earthquake near Scotty\'s Junction, NV';
      $NAVIGATION	= true;
      include	'template.inc.php';
      }
?>
<p>
	<video width="563" height="460" controls>
    <source src="media/sjamovie.mp4" type="video/mp4">
  Your browser does not support the video tag.
  </video>
  <!--<video src="media/sjamovie.mp4" poster="images/sanjose.gif" alt="Click to view San Jose animation" width="563" height="460" controls></video>-->
</p>

<p>
	This animation displays seismic waves propagating across the San Jose Dense Seismic Array on a map of the area (rotated 45 degrees so that North is to the upper right). Circles denote the locations of stations of the array. For each frame the colors are based on the resulting amplitudes of the bandpass-filtered accelerograms at each site, and then spatially-interpolated between sites.
</p>

<p>
	These are actual data, not simulations.
</p>

<p>
	This animation shows the ground motions (east-west component filtered between 4 and 8 sec period) for a M5.6 earthquake 420 km east of the array in Scotty's Junction Nevada. Red colors correspond to high eastward particle motion; blue represents high westward particle motion. The time shown is the time after the origin time of the earthquake.
</p>

<p>
	Above the map are two seismograms. The one to the left is the seismogram for station N45 (colored circle) a site in the Santa Clara valley near the top of the map. The seismogram on the right is for the rock site near the right edge of the map. Both seismograms are plotted with the same scale and are the east-west component of acceleration filtered at 4-8 sec period. The seismograms are synchronized to the animation of the map view.
</p>

<p>
	The animations show the S-wave propagating from the lower right corner to the upper left corner starting about 122 sec after the origin time. This arrival is traveling east to west across the array, from the direction of the earthquake.
</p>

<p>
	Starting at about 140 sec there are packets of energy traveling across the array from the lower left portion of the map to the upper right, i.e., from approximately south to north. These arrivals form the largest phases in the seismogram to the left for the site in the valley and for other valley sites.
</p>

<p>
	These later arrivals are also observed for other regional earthquakes east of the array at closer distances, with the same time delay after the S-wave. A cross correlation analysis also shows that these arrivals are traveling from the south-southwest and have low apparent velocities indicating that they are basin surface waves.All of this evidence indicates that these large phases are basin surface waves that were likely generated by scattering of Incident S-waves at the edge of the Santa Clara Valley south of the array. It is remarkable that the largest amplitude phase at long periods at many of the valley sites is a basin surface wave propagating from a direction about 70 degrees different from that to the epicenter of the earthquake.
</p>

<p>
	Scientific Staff: Dave Carver, Edward Cranswick, Tom Bice and Russell Sell deployed the array. The San Jose Array was funded by Pacific Gas and Electric Co.
</p>

<h2>References</h2>
<ul class="referencelist">
  <li>
    Frankel, A.,  Carver, D., Cranswick, E., Bice, T., Sell, R., and Hanson, S.
    (2001), Observations of basin ground motions from a dense array in San Jose,
    California, Bulletin of the Seismological Society of America., v. 91, pp. 1-12.
  </li>
</ul>
