<?php
if (!isset($TEMPLATE)) {
  $TITLE = 'Repeating Earthquakes';
  $HEAD = '';
  $FOOT = '';
  $NAVIGATION = true;

  include 'template.inc.php';
}
?>

            <p>The modern era of scientific earthquake prediction began, perhaps, in the mid- to late 1970's. In the winter of 1975, Chinese officials had ordered the evacuation of the city of Haicheng (population about 1 million) in the Liaoning Province of northeast China, based on reports from scientists and lay observers in a wide region of unusual observations. Over a period of months, changes in land elevation and ground water levels had been reported, and there were widespread accounts of peculiar animal behavior and other possible precursors to an earthquake. A regional increase in seismicity (which later was recognized as foreshocks) had triggered a low-level alert. Subsequently, an increase in foreshock activity triggered the evacuation warning. The magnitude 7.3 earthquake struck the region days later on February 4, 1975. Physical injury and death affected only a small fraction of the total population; 2,041 people died, 27,538 were injured. It was estimated that the number of fatalities and injuries would have exceeded 150,000 if no earthquake prediction and evacuation had been made. </p>
            <p> The optimism inspired by this success was short-lived. The following year, on July 28, 1976, a magnitude 7.6 earthquake struck the city of Tangshan, a thriving industrial city with approximately one million inhabitants, without warning. None of the precursors observed near Haicheng were observed this time. The earthquake caused an estimated 250,000 fatalities and 164,000 injured. A team of scientists from the U.S. visited laboratories in China in 1976 to investigate the Haicheng prediction. Their report concluded that the 1975 Haicheng prediction was based mainly on the pronounced foreshock sequence; other aspects of the described methodology were more difficult to assess. </p>
            <p> Interest in the possibility of a dependable method for earthquake prediction had increased among the scientific community. In 1977, Congress created the<a href="http://www.nehrp.gov/"> National Earthquake Hazards Reduction Program</a> (NEHRP). Currently, the Program involves four agencies: the <a href="http://www.usgs.gov">US Geological Survey</a> (USGS), <a href="http://www.nsf.gov">National Science Foundation</a>, (NSF) <a href="http://www.fema.gov">Federal Emergency Management Agency</a> (FEMA) and the <a href="http://www.nist.gov">National Institute for Standards and Technology</a> (NIST). The Program focuses on both the prediction of shaking and the mitigation of risk, and includes research in earthquake science, earthquake engineering and social science. At their peak, earthquake prediction studies accounted for approximately 20 percent of the USGS-administered part of the Program. Currently, the earthquake prediction activities under NEHRP are concentrated in the Parkfield Earthquake Prediction Experiment.</p>
