<?php
if (!isset($TEMPLATE)) {
  $TITLE = 'Fluids and Earthquakes';
  $HEAD = '';
  $FOOT = '';
  $NAVIGATION = true;

  include 'template.inc.php';
}
?>

            <p>A Summary of Recent Investigations excerpted from &quot;The Parkfield, California, Earthquake Experiment, An Update in 2000&quot;, Evelyn Roeloffs [<a href="http://www.iisc.ernet.in/currsci/nov102000/1226.pdf">PDF</a>]
</p>
            <p>Fault-zoned fluids play an important role in generating earthquakes. High pressure fluid in the fault zone may reduce the frictional strength of the fault. Variations in fluid pressure may affect the timing of earthquakes (<a href="/learn/parkfield/scientific.php#Miller96">Miller, 1996</a>). Data collected at Parkfield allow some of these hypotheses to be tested. </p>
            <p> Several studies of seismic wave velocities around Parkfield have identified bodies at seismogenic depths with velocities or attenuation that could be caused by high fluid pressure. Between depths of 6 and 10 km, there is a 3-km-wide zone of low Vp (<a href="/learn/parkfield/scientific.php#Eber93">Eberhart-Philips, D. 1993</a>), relatively lower Vs, and therefore high Vp:Vs ratio (1.9 - 2.0) (<a href="/learn/parkfield/scientific.php#Mich91">Michelini, A. 1991</a>) immediately northeast of the active fault surface as defined by microseismicity. Along strike of the San Andreas fault, this body extends from the 1966 hypocenter about 5 km to the southeast. This zone is also characterized by high seismic wave attenuation. The seismic wave propagation characteristics of this body are consistent with high fluid content, but do not require pressure in the fluid to be elevated. High fluid pressure in a 1-km-deep borehole on the NE side of the San Andreas fault in this area, however, shows that there is at least localized overpressure at depth. </p>
            <p> Unsworth et al. (<a href="/learn/parkfield/scientific.php#Unsworth97">1997</a>) conducted a magnetotelluric transect across the San Andreas fault on Middle Mountain directly above the northeast limit of the high Vp:Vs body. The prominent finding is a vertical zone of low resistivity along the fault trace, about 500 m wide, extending to about 4000 m depth, with higher resistivities, or narrow width, at greater depth. This zone contains significant areas where the resistivity is about 1 ohm-meter, a range too low to be reached through the presence of clays or serpentine alone, and therefore strongly indicates a network of interconnected pore space. Unsworth et al. (<a href="/learn/parkfield/scientific.php#Unsworth97">1997</a>) estimated the amount of fluid present as either 9 to 30% fluid-filled porosity, or total width of the fluid-filled macroscopic cracks,
assuming that the fluid is a brine of 30,000 ppm chloride similar to that found in the deepest drillhole to date near Parkfield. Li et al.(<a href="/learn/parkfield/scientific.php#LiYL90">1990</a>)
had previously inferred the existence of a seismic low-velocity zone of similar width to model seismic trapped aces in the fault zone. The seismic low-velocity zone would require at least some of the fault-zone fluid to be distributed in pores rather than localized in cracks. </p>
            <p> Studies of gas flux have been made at Parkfield to investigate the hypothesis that CO<sub>2</sub> outgassing from deep sources could provide the fluid pressurization needed to account for low frictional stress across the San Andreas fault. Lewicki and Brantley measured CO<sub>2</sub> fluxes and concentrations along 16 fault-crossing transects, and found high CO<sub>2</sub> flux anomalies on 12 tracts within about 40 m of the fault race. The high-flux locations however were not always the
sites of the highest CO<sub>2</sub> concentrations, and isotopic studies indicate the CO<sub>2</sub> is of biogenic origin. Thus the fault zone represents a high permeability or diffusivty conduit for escape of biogenic CO<sub>2</sub>, with no evidence for deeper degassing. This study, which included transects
on Middle Mountain close to the MT profile and directly above the 1966 epicenter, suggests that the fault at shallow depth is a conduit for vertical flow, rather than a la permeability zone that would help maintain high fluid pressure at depth. The previous studies show that bodies that might contain fluids
are likely present, and that the hydrologic properties of the fault zone are distinct from those of its surroundings. Johnson and McEvilly (<a href="/learn/parkfield/scientific.php#Johnson95">1995</a>)
considered how microseismicity features might reveal fluid involvement. The clusters in which similar microearthquakes repeat at fairly regular intervals could be sites of unique fluid pressure, rather than lithologic conditions. Some bursts of localized microseismicity include sequences of hypocentres
successively further from the initial even over periods of hours and distance of 1 to 2 m. Although moment tensor decomposition is problematic for such small events, there are some events with bob-double-couple components that indicate flattening of the source. Both features are consistent with hydrofracture of high-fluid-pressure 'pods, and less consistent with failure of isolated impermeable asperities surrounded by a generally high-fluid pressure fault plane. </p>
            <p> Evidence to date for fluid-driven seismicity at Parkfield includes seismic velocities consistent with the presence of fluids in the fault zone, including the 1966 hypocentre, and with additional corroboration from the resistivity structure shallower than 4 km. Seismicity pasterns that resemble those expected from diffusion of localized pore pressure have accord. Gas studies show that at shallower depths, the fault is a zone of relatively high vertical permeability. The source of fault-zone fluids and the level of in situ pressures remain unknown, and are important scientific goals of proposed deep drilling at Parkfield.</p>
