<?php
      //	Author:	Tiffany Kalin
      //	Contact:
      //	Last	modified:	9/15/2016
      if	(!isset($TEMPLATE))	{
      $TITLE	=	'Can It Happen Here?';
      $NAVIGATION	= true;
      include	'template.inc.php';
      }
?>

<h2>Could a tsunami such as the one that affected the Indian Ocean on December, 26, 2004 happen in the United States? </h2>

<p>
  Soon after the devastating tsunami in the Indian Ocean on December 26, 2004, many people have asked, could such a tsunami happen in the United States? This web page summarizes what we know about tsunamis that have struck the U.S. in the past, providing a foundation for estimating tsunami likelihood in the future. Below, we outline the sources of data that can help answer the question, and then indicate when and how large tsunamis have been for specific regions of the U.S.
</p>

<h4>What are Tsunamis?</h4>
<p>
  Tsunamis are ocean waves caused by large earthquakes and landslides that occur near or under the ocean. Scientists do not use the term &quot;tidal wave&quot; because these waves are not caused by tides. Tsunami waves are unlike typical ocean waves generated by wind and storms. When tsunamis approach shore, the behave like a very fast moving tide that extends far inland. A rule of thumb is that if you see the tsunami, it is too late to out run it. Most tsunamis do not &quot;break&quot; like the curling, wind-generated waves popular with surfers. Even &quot;small&quot; tsunamis (for example, 6 feet in height) are associated with extremely strong currents, capable of knocking someone off their feet. Because of complex interactions with the coast, tsunami waves can persist for many hours. As with many natural phenomena, tsunamis can range in size from micro-tsunamis detectable only by sensitive instruments on the ocean floor to mega-tsunamis that can affect the coastlines of entire oceans, as with the Indian Ocean tsunami of 2004. If you hear a tsunami warning or if you feel strong shaking at the coast or very unusual wave activity (e.g., the sea withdrawing far from shore), it is important to move to high ground and stay away from the coast until wave activity has subsided (usually several hours to days). For more general information on tsunamis and what to do during a tsunami warning, please visit sites sponsored by <a
  href="https://www.ready.gov/tsunamis"><!--http://www.fema.gov/areyouready/tsunamis.shtm-->FEMA</a>, the <a
  href="http://itic.ioc-unesco.org/index.php?option=com_content&view=article&id=1169&Itemid=2017">National Weather Service</a>, <a href="http://www.wsspc.org/resources-reports/tsunami-center/">state agencies</a>, <a href="http://www.pmel.noaa.gov/tsunami/">NOAA</a>, and the <a
  href="http://walrus.wr.usgs.gov/tsunami/">USGS</a>.
</p>

<h4>Data We Can Use to Answer the Question</h4>
<p>
  There are three primary sources of information we can use to answer the question Could it Happen Here? (1) tsunami catalogs of historic events, (2) the age of geologic deposits left by <a
  href="http://quake.wr.usgs.gov/research/geology/index.html">great earthquakes </a>and <a href="http://walrus.wr.usgs.gov/tsunami/itst.html">tsunamis</a>, and (3) <a
  href="http://walrus.wr.usgs.gov/tsunami/">computer simulations</a> of tsunamis from potential great earthquake and landslides around the world. In this web page, we will focus mainly on the historic information (1). The <a
  href="http://www.ngdc.noaa.gov/hazard/tsu.shtml">National Centers for Environmental Information (formerly the National Geophysical Data Center)</a> (part of <a href="http://www.noaa.gov/">NOAA</a>), maintains a worldwide catalog of historic tsunamis. This catalog includes two types of measurements: runup observations from eyewitness accounts and wave height readings from tide gauge stations, most often located in harbors. In scientific terms, <b>runup</b> refers to the vertical height a wave reaches above a reference sea level as it washes ashore. <b>Wave height</b> is the vertical measurement of the wave before it reaches shore. <b>Inundation distance</b> is the horizontal distance a tsunami reaches landward from the shoreline.
</p>

<h4>Hawai'i</h4>
<p>
  Hawai'i has a long recorded history of tsunamis. Tsunamis have come from both earthquakes around the Pacific rim or <a
  href="http://pubs.usgs.gov/publications/text/dynamic.html">&quot;Ring of Fire&quot;</a>, termed <b>teletsunamis</b> or far-field tsunamis, and from earthquakes and landslides near Hawai'i, termed <b>local tsunamis</b>. The Pacific Disaster Center reports that tsunamis have accounted for more lost lives in Hawaii than the total of all other local disasters (<a
  href="http://www.pdc.org/">http://www.pdc.org</a>). In the 20th century, an estimated 221 people have been killed by tsunamis on the islands of Hawaii. One of the largest and most devastating tsunamis Hawai'i has experience was a teletsunami in <a
  href="http://cwis.usc.edu/dept/tsunamis/alaska/1946/webpages/index.html">1946</a> ffrom an earthquake along the Aleutian subduction zone. Runup heights reached a maximum of 33-55 feet and 159 people were killed. This tsunami caused more than $26 million damage. Other important teletsunamis include one from the <a
  href="http://geopubs.wr.usgs.gov/circular/c1187/">1960</a> M=9.5 earthquake in southern Chile and one from the <a href="http://wcatwc.arh.noaa.gov/64quake.htm">1964</a> M=9.2 earthquake in the Gulf of Alaska. The May 22, 1960 Chile earthquake generated a 35 foot wave causing 61 deaths and $23 million in damage. Other significant tsunamis in Hawaii include: 1952 (M=9.0) Kamchatka, USSR earthquake ($1 million damage), 1957 (M=9.1) Aleutian Islands earthquake ($5 million damage).
</p>

<p>
  Local tsunamis have also hit Hawai'i, primarily from earthquakes and large-scale <a
  href="http://hvo.wr.usgs.gov/earthquakes/destruct/1975Nov29/deformation.html">subsidence</a> along the south flank of Kiluea. The largest of these were in <a
  href="http://hvo.wr.usgs.gov/earthquakes/destruct/">1868</a> that killed 81 people and in <a
  href="http://hvo.wr.usgs.gov/earthquakes/destruct/1975Nov29/tsunami.html">1975</a>. Overall, approximately 32 tsunamis with runup &gt; 1 meter have occured in Hawai'i since 1811.
</p>

<h4>Alaska</h4>
<p>
  Because Alaska, including the Aleutian Islands, is bordered to the south by a major subduction zone capable of generating large earthquakes, Alaska has experienced a number of damaging tsunamis. Two megathrusts have ruptured in great earthquakes: the Aleutian and Alaskan subduction zones. The Aleutian subduction zone ruptured segments in 1957 (M=9.1), 1965 (M=8.7), and 1986 (M =8.0). The Alaskan subduction zone ruptured in 1938 (M=8.2), 1946 (M=7.3), 1948 (M=7.5), and 1964 (M=9.2). By far, the one that stands out is the tsunami generated from the <a href="http://wcatwc.arh.noaa.gov/64quake.htm">1964</a> M=9.2 earthquake that occurred in the Gulf of Alaska. Not only was a Pacific-wide tsunami generated from this great earthquake, but landslides in the coastal fjords such as <a
  href="http://www.usc.edu/dept/tsunamis/alaska/1964/webpages/1964valdez.html">Valdez</a> also generated localized, but extremely damaging waves. The 1964 tsunami caused damage and loss of life across the Pacific. The <a href="http://wcatwc.arh.noaa.gov/">West Coast &amp; Alaska Tsunami Warning Center</a>, Palmer Alaska indicates that the 1964 tsunami was the most disastrous tsunami to hit the U.S. West Coast. Many fatalities and financial losses were caused by with the tsunami: Alaska- 106 deaths and $84 million damage; Washington- minor damage along the coast; Oregon- 4 deaths and $0.7 million damage; California- 13 deaths and $10 million damage.
</p>

<p>
  Alaska's famous fjords are also the source for another type of &quot;tsunami&quot;: one in which landslides perched on the steep walls of fjords catastrophically fail and splash into the water, generating extreme wave heights, such as the <a
  href="http://www.usc.edu/dept/tsunamis/alaska/1958/webpages/lituyacloseup.html">1958</a> Lituya Bay landslide. Again this is a localized phenomenon that does not produce teletsunamis as with tsunamis produced by great earthquakes. Overall, approximately 16 tsunamis of all sources with runup &gt; 1 meter have occurred in Alaska since 1853.
</p>

<h4>U.S. West Coast</h4>
<p>
  The historic record of tsunamis along the U.S. west coast includes mainly teletsunamis, generated from large earthquakes around the Pacific Rim. &nbsp;Nevertheless, potentially tsunamigenic fault structures do exist locally offshore the U.S. west coast, most noteably from the Cascadia subduction zone.&nbsp; The Cascadia subduction zone is a 750 miles (1,200 km) long offshore fault that extends from northern California to southern Canada and accommodates motion between the Pacific and North American plates at a rate of about 40 mm/yr (1.6 inches/year). This subduction zone is thought to have last ruptured in a <a href="http://quake.wr.usgs.gov/prepare/factsheets/PacNW/">M 9.0 earthquake</a> in <a href="http://europa.agu.org/?view=article&uri=/journals/jb/jb0311/2003JB002521/2003JB002521.xml&t=Cascadia,subduction,1700">1700</a>; the resulting tsunami was recorded in northern Japan historical accounts. However, this fault has been quiescent since that large rupture. It has generated no great earthquakes (M&gt;8) and very few large earthquakes (M&gt;6) during the 150 years of recorded history. The 1992 Petrolia earthquake (M=7) is the largest modern event that is thought to have ruptured the plate interface. Geologic evidence of submerged vegetation indicates that large or great earthquakes (M=8-9) have occurred on average every 500 years along this zone. Great ruptures along this subduction zone would most likely cause local and possibly ocean-wide tsunamis that could affect the western United States.
</p>

<p>
  Of the teletsunamis that have struck the West Coast, the <a href="http://wcatwc.arh.noaa.gov/64quake.htm">1964</a> Gulf of Alaska tsunami caused the most extensive damage, particularly in <a href="http://wcatwc.arh.noaa.gov/web_tsus/19640328/narrative8.htm">Crescent City</a>, California. Overall, approximately 28 tsunamis with runup &gt; 1 meter have occurred along the U.S. West Coast since 1812.
</p>

<h4>U.S. Gulf Coast</h4>
<p>
  In historic times, tsunami waves recorded along the Gulf Coast have all been less than 1 meter. Some of the reports are from the 1964 Gulf of Alaska earthquake recorded in Louisiana and Texas and are technically termed a seiche. A <b>seiche</b> is an oscillation of a body of water, typically caused by atmospheric disturbances, but in this case caused by the ground motion from the earthquake. Seiches can also occur in lakes from earthquake movements. There are a couple of early 20th-centutry reports of tsunami waves from Caribbean earthquakes along the Gulf Coast that are difficult to evaluate, but the wave heights all appear to be less than 1 meter.
</p>

<h4>U.S. East Coast</h4>
<p>
  Because the only major subduction zones in the Atlantic Ocean&nbsp;are along the Caribbean Sea, there has been a relatively low frequency of tsunamis compared to the Pacific Ocean. The most famous Atlantic tsunami is the <a href="http://en.wikipedia.org/wiki/1755_Lisbon_earthquake">1755</a> Lisbon tsunami, that was generated by an earthquake on a fault offshore Portugal. The most noteworthy North America local tsunami is the <a
  href="http://www.seismo.nrcan.gc.ca/damage/1929/1929_e.php">1929</a> M=7.3 Grand Banks earthquake near Newfoundland, Canada. This is a complex event; most, if not all, of the tsunami energy may have been triggered by a submarine landslide. The maximum tsunami runup from this event was 2-7 meters concentrated on the coast of Newfoundland, though it was recorded as far south as South Carolina. Like the Gulf Coast, there a couple of reports of small tsunamis from Caribbean earthquakes, all less than 1 meter.
</p>

<h4>Puerto Rico / U.S. Virgin Islands</h4>
<p>
  Puerto Rico and the U.S. Virgin Islands are more susceptible than other locations in the eastern U.S., because of a subduction zone that lies beneath the Caribbean Sea, capable of generating large earthquakes. Tsunamis have impacted Puerto Rico and the Virgin Islands more than 6 times in recorded history. The web site of the <a href="http://poseidon.uprm.edu/">Puerto Rico Tsunami Warning and Mitigation Program</a> also asks whether a tsunami similar to the one in the Indian Ocean could hit the Caribbean region. An event in <a
  href="http://www.usc.edu/dept/tsunamis/caribbean/webpages/1867viindex.html">1867</a> off the Virgin Islands is thought to have generated waves 12 meters high. The tsunami with the greatest amount of damage in Puerto Rico was in <a
  href="http://www.usc.edu/dept/tsunamis/caribbean/webpages/1918prindex.html">1918</a> from an earthquake off the Mona Passage. With a maximum runup of 6 meters, the tsunami itself killed 40 people with an additional 76 people killed by the earthquake. The Caribbean region as a whole has a <a
  href="http://isis.uwimona.edu.jm/uds/Tsunami_Lander.html">history</a> of other earthquakes that have caused damaging tsunamis.
</p>

<h4>Other U.S. territories</h4>
<p>
  <a href="http://www.ngdc.noaa.gov/seg/hazard/tsupub.shtml">Other territories</a> of the United States are located adjacent to large subduction zones. Guam and Marianas Islands are located next to the Marianas trench. American Samoa is affected by earthquakes about 100 miles away along the Tonga-Kermadec trench.
</p>

<h4>References</h4>
<p>
  These historic reports are based largely on the tsunami catalog maintained by the <a href="http://www.ngdc.noaa.gov/ngdc.html">NGDC</a>. Paper copies of the tsunami catalogs can be ordered from the <a
  href="http://www.ngdc.noaa.gov/seg/hazard/tsupub.shtml">publications web site</a>. (See accompanying <a
  href="http://www.ngdc.noaa.gov/ngdcinfo/privacy.html#copyright.html">Copyright</a> notice.) In addition we have used information from the Pacific Tsunami Warning Center (Hawaii and Alaska) and the Pacific Disaster Center.
</p>
