<?php
// Author: Lisa Wald
// Contact: Paul Earle
  if (!isset($TEMPLATE)) {
    $TITLE = 'Sonic Booms';
    $NAVIGATION = true;
    include 'template.inc.php';
  }
?>

<h2>How Can You Tell the Difference Between a Sonic Boom and an Earthquake on a Seismogram?</h2>

<p>
  Sonic booms aren’t always recorded on seismic instruments, but when they are, this is how we identify and confirm that the signal is a sonic boom rather than an earthquake.
</p>
<p>
  First, we either see nothing or see a fairly short high-frequency signal on our records that does not look like an earthquake.  On rare occasions, we see the signal on multiple stations, and the move-out, or time difference, matches the speed of sound in air, which is much slower than the speed of seismic waves in rock.
</p>
<p>
  The next clue is that the felt reports come from a very wide area, typical of a fairly big earthquake, but there is no such event on our records.  Reports of a bang or boom is somewhat of a clue, although shallow earthquakes often sound like booms or bangs, so that is not an ironclad indicator.
</p>
<p>
  From just those points alone, we can be pretty sure that it is some kind of atmospheric source, such as a sonic boom, artillery fire or something like a meteorite or bolide explosion.  The artillery fire isn't generally as loud as a sonic boom and is not observed over such a wide area.  On the other hand, bolides are often reported as very bright lights in the sky along with the sound and ground motion.  A very small earthquake or cavity collapse such as a rockfall in a cave also produces very small signals on the seismogram, but they tend to look quite different and the felt reports tend to be from a small focused area instead of over a wide area.
</p>
<p>
  The final step is that someone with sufficiently high rank in the military announces that one or some of their planes were in the area.  This last step is most likely to happen if the media and the public are sufficiently persistent in asking about it. In most cases, the best result is to have someone confirm that there were planes in the area that "might have gone supersonic."
</p>

<h2>Some Interesting Facts About Sonic Booms</h2>
<ul>
  <li>
    Most sonic booms aren't felt on land (most supersonic training flights are out over the ocean).
  </li>
  <li>
    Atmospheric events are difficult to detect with seismographs because they usually transfer very little seismic energy into the ground.
  </li>
  <li>
    Atmospheric conditions like temperature inversions and calm surface winds can make sound propagate farther than normal.
  </li>
  <li>
    Aircraft actually produce two booms, but they usually arrive so close together that they're indistinguishable.
  </li>
  <li>
    "Under certain aircraft operating conditions (e.g., acceleration, dives, turns, and climbs), the sonic boom conoids generated by the aircraft may intersect one another. This effect is known as sonic boom focusing. Such focusing may also result from refraction effects caused by variations in atmospheric sound and wind speed. Focused sonic booms may be of much greater intensity than unfocused booms and are typically generated by fighter aircraft in "dogfight" maneuvers." (<a href="http://www.nonoise.org/library/animals/litsyn.htm#2.2.2%20Sonic%20Booms">USFWS</a>)
  </li>
  <li>
    USGS instruments are not designed to detect or analyze atmospheric phenomena, and atmospheric research is not part of the USGS mission.
  </li>
  <li>
    If you type "sonic boom" into our website search, you'll get a listing of eventpages for sonic booms, though it certainly isn't comprehensive. Since these events are given a magnitude of 0.0, you will need to include ALL magnitudes in your Latest Earthquakes Map and List to see them.
  </li>
</ul>

<h2>For More Information</h2>
<ul>
  <li>
    <a href="http://www.holloman.af.mil/soundoffreedom.asp">Sonic Boom info from Holloman Air Force Base</a>
  </li>
  <li>
    <a href="booms.php">Earthquake Booms, Seneca Guns, and Other Sounds</a>
  </li>
  <li>
    <a href="http://blog.weatherflow.com/sonic-boom-felt-throughout-charleston-sc-on-january-26-2016/">Sonic Boom Felt Throughout Charleston, SC on January 26, 2016</a> - includes diagrams about atmospheric effects
  </li>
  <li>
    <a href="http://www.nasa.gov/centers/armstrong/news/FactSheets/FS-016-DFRC.html">NASA Fact Sheet about Sonic Booms</a>
</ul>
