<?php
      //	Author:	Tiffany Kalin
      //	Contact:
      //	Last	modified:	10/5/2016
      if	(!isset($TEMPLATE))	{
      $TITLE	=	'Northern Sumatra M9.0 - December 26, 2004';
      $NAVIGATION	= true;
      include	'template.inc.php';
      }
?>
<!--want?-->
<style>
	.question {
	font-weight: bold;
	}

</style>

<ul>

	<li>
		<p class="question">
			How long did the magnitude 9.0 earthquake off the west coast of northern Sumatra shake? (What was the duration?)
		</p>

		<p>
			The actual rupture duration on the fault (the time it took for the earthquake to take place on the fault and rupture the entire length) was approximately 3 to 4 minutes. The exact length of time that people felt the shaking varied from place to place, depending on their distance to the fault, and other factors, such as what type of bedrock they were on, what the crustal structure was below them and between them and the fault, etc. In northern Sumatra , which lies almost above the fault, shaking may have been experienced for up to several minutes.
		</p>
	</li>

	<li>
		<p class="question">
			How much energy was released by the magnitude 9.0 earthquake off the west coast of northern Sumatra?
		</p>
		<p>
			Es 20X10^17 Joules, or 475,000 kilotons (475 megatons) of TNT, or the equivalent of 23,000 Nagasaki bombs.
		</p>
	</li>

	<li>
		<p class="question">
			What was the size of the fault that produced the magnitude 9.0 earthquake off the west coast of northern Sumatra?
		</p>
		<p>
			An initial estimate of the size of the rupture that caused the earthquake is obtained from the length of the aftershock zone, the dimensions of historical earthquakes, and a study of the elastic waves generated by the earthquake. The aftershocks suggest that the earthquake rupture had a maximum length of 1200 -- 1300 km parallel to the Sunda trench and a width of over 100 km perpendicular to the earthquake source. An early estimate from the study of elastic waves show the majority of slip was concentrated in the southernmost 400 km of the rupture.
		</p>
	</li>

	<li>
		<p class="question">
			What is the plate tectonic setting of Andaman Island?
		</p>
		<p>
			Andaman Island and the great sweep of the Sunda Arc, over 3,000 kilometers from NW Sumatra to the Banda Sea, results from the subduction of Indian Ocean crust beneath the Asian Plate. This arc includes 76 percent of the region's volcanoes, and those on either end are tectonically more complex. To the NNW, the basaltic volcanism results from short spreading centers, and to the east the Banda Arc reflects Pacific Ocean crust sub ducted westward. North of this arc, tectonic complexity increases, with converging plate fragments forming multiple subduction zones mainly oriented noth-south that in turn produce the Sulawesi-Sangihe volcanoes on the west and Halmahera on the east of the collision zone.
		</p>

		<p>
			Andaman Island lies in a very active earthquake zone.
		</p>
	</li>

	<li>
		<p class="question">
			What was the maximum displacement on the rupture surface between the plates from the magnitude 9.0 earthquake off the west coast of northern Sumatra?
		</p>
		<p>
			The maximum displacement estimated from a preliminary study of the seismic body waves is 20 meters.
		</p>
	</li>

	<li>
		<p class="question">
			What was the maximum displacement of the sea bottom above the magnitude 9.0 earthquake source off the west coast of northern Sumatra?
		</p>
		<p>
			The displacement of the ground surface will be related to, but somewhat less than, the displacement on the earthquake fault at depth. In places, the block of crust beneath the sea floor and overlying the causative fault is likely to have moved on the order of 10 meters to the west-southwest and to have been uplifted by several meters.
		</p>
	</li>

	<li>
		<p class="question">
			How has the occurrence of the magnitude 9.0 earthquake off the west coast of northern Sumatra affected the probability of another great earthquake?
		</p>
		<p>
			The occurrence of this earthquake will have produced a redistribution of tectonic stresses along and near the boundary between the India plate and the Burma plate. In some areas, this redistribution of stresses will be such as to shorten the time to the next big earthquake compared to what would have been the case if the earthquake had not happened. In other areas, the redistribution of stresses will be such as to increase the time to the next big earthquake. Once the distribution of slip along the earthquake fault has been mapped, it will be possible to estimate the areas that were moved closer to future failure and those that were moved farther from future failure. It is not yet possible, however, to reliably estimate when the future failure will occur in a given area or how large will be the resulting earthquake.
		</p>
	</li>

	<li>
		<p class="question">
			The magnitude 9.0 earthquake off the west coast of northern Sumatra occurred within three days of a magnitude 8.1 earthquake in the Macquarie Islands. Is there any relation between the two earthquakes?
		</p>
		<p>
			The occurrence of two great earthquakes within such a short space of time is indeed striking. However, there is not a well-established mechanism by which the two earthquakes might be causally related. The two earthquakes are very far from one another and occurred on different plate boundaries. The Macquarie ridge forms part of the Pacific-Australian plate boundary and is a predominantly right-lateral, strike-slip transform fault with a component of convergence that connects two subduction zones to the north and south. The Sumatra megathrust earthquake occurred on the interface of the India and Burma plates and was caused by the release of stresses that develop as the India plate sub ducts beneath the overriding Burma plate. The occurrence of the two, widely separated, great earthquakes within three days may have been a statistical coincidence.
		</p>
	</li>

	<li>
		<p class="question">
			What effect did the magnitude 9.0 earthquake off the west coast of northern Sumatra have on the rotation of the earth?
		</p>
		<p>
			While this question is a little outside the earthquake role of the USGS, scientists at NASA's Jet Propulsion Laboratory (JPL) who work with the USGS, have told us that the effects on the Earth's rotation from an earthquake even of this magnitude is much too small to be observed. The length of the day can be measured with an accuracy of about 20 microseconds and calculations of the source properties of the earthquake showed the change in the length of the day to be -2.676 microseconds, or in other words, less than can be effectively measured.
		</p>

		<p>
			If you want a more complete and technical answer to this question, Richard Gross at JPL offers the following:
		</p>

		<p>
			JPL has modeled the coseismic effect on the Earth's rotation of the December 26 earthquake in Indonesia by using the PREM model for the elastic properties of the Earth and the Harvard centroid-moment tensor solution for the source properties of the earthquake. The result is:
		</p>

		<ul>
			<li>change in length of day: -2.676 microseconds</li>
			<li>polar motion excitation X : -0.670 milliarcseconds</li>
			<li>polar motion excitation Y: 0.475 milliarcseconds</li>
		</ul>

		<p>
			Since the length of the day can be measured with an accuracy of about 20 microseconds, this model predicts that the change in the length-of-day caused by the earthquake is much too small to be observed. And, since the location of the earthquake was near the equator, this model predicts that the change in polar motion excitation is also rather small, being about 0.82 milliarcsecond in amplitude. Such a small change in polar motion excitation will also be difficult to detect.
		</p>

		<p>
			<strong>Also see:</strong>
			<br>
			<a href="http://www.nasa.gov/home/hqnews/2005/jan/HQ_05011_earthquake.html">NASA Details Earthquake Effects on the Earth </a>
			<br>
			<a href="http://science.nasa.gov/headlines/y2005/10jan_earthquake.htm?list720139">How the Earthquake Affected the Earth - NASA </a> <!--broken link-->
		</p>

	</li>

	<li>
		<p class="question">
			What was the background seismicity in the region before the magnitude 9.0 earthquake off the west coast of northern Sumatra?
		</p>
		<p>
			This table represents the number of earthquakes in the aftershock zone of the magnitude 9.0 earthquake on 12/26/04 for the ten previous years.
		</p>

	<!--table formatting?-->
		<table cellpadding="0" cellspacing="0" id="statistics" width="80%">
	    <tbody>
				<tr>
	        <td width="111" valign="top" align="center"><strong>YEAR</strong> </td>
	        <td width="111" valign="top" align="center"><strong>Magnitude <br>
	            5.5 &amp; larger events</strong></td>
	        <td width="111" valign="top" align="center"><strong>Magnitude <br>
	            5.0 &amp; larger events</strong></td>
	        <td width="111" valign="top" align="center"><strong>Magnitude <br>
	            4.5 &amp; larger events</strong></td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center"><strong>1995</strong></td>
		        <td width="111" valign="top" align="center">2</td>
		        <td width="111" valign="top" align="center">7</td>
		        <td width="111" valign="top" align="center">35</td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center"><strong>1996</strong></td>
		        <td width="111" valign="top" align="center">2</td>
		        <td width="111" valign="top" align="center">9</td>
		        <td width="111" valign="top" align="center">36</td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center"><strong>1997</strong></td>
		        <td width="111" valign="top" align="center">2</td>
		        <td width="111" valign="top" align="center">11</td>
		        <td width="111" valign="top" align="center">37</td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center"><strong>1998</strong></td>
		        <td width="111" valign="top" align="center">1</td>
		        <td width="111" valign="top" align="center">8</td>
		        <td width="111" valign="top" align="center">38</td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center"><strong>1999</strong></td>
		        <td width="111" valign="top" align="center">3</td>
		        <td width="111" valign="top" align="center">11</td>
		        <td width="111" valign="top" align="center">34</td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center"><strong>2000</strong></td>
		        <td width="111" valign="top" align="center">5</td>
		        <td width="111" valign="top" align="center">12</td>
		        <td width="111" valign="top" align="center">44</td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center"><strong>2001</strong></td>
		        <td width="111" valign="top" align="center">4</td>
		        <td width="111" valign="top" align="center">9</td>
		        <td width="111" valign="top" align="center">36</td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center"><strong>2002</strong></td>
		        <td width="111" valign="top" align="center">11</td>
		        <td width="111" valign="top" align="center">25</td>
		        <td width="111" valign="top" align="center">91</td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center"><strong>2003</strong></td>
		        <td width="111" valign="top" align="center">6</td>
		        <td width="111" valign="top" align="center">20</td>
		        <td width="111" valign="top" align="center">64</td>
		    </tr>
		    <tr>
		        <td width="111" valign="top" align="center">2004</td>
		        <td width="111" valign="top" align="center">4</td>
		        <td width="111" valign="top" align="center">14</td>
		        <td width="111" valign="top" align="center">67</td>
		    </tr>
		</tbody>
	</table>


		<p>
			The numbers of earthquakes located in 2004 does NOT reflect the main shock or aftershocks from the 9.0. The region encompasses a rectangular box which extends from 2N to 14N and from 92E to 98E. These statistics were obtained from the USGS PDE earthquake catalog search page.
		</p>
	</li>

	<li>
		<p class="question">
			How come the 12/23/04 M8.1 Macquarie Island earthquake didn't produce a tsunami? What was the difference from the magnitude 9.0 earthquake off the west coast of northern Sumatra?
		</p>
		<p>
			A tsunami is a sea wave of local or distant origin that can be generated when the sea floor abruptly deforms and vertically displaces overlying water. Such a displacement can occur when an earthquake ruptures oceanic lithosphere. When the opposite sides of a fault are inclined and have a vertical component of motion, we have an earthquake with dip-slip faulting. When the opposite sides of a fault are vertical and move horizontally, we have an earthquake with strike-slip faulting. Given two earthquakes of the same size, the one that has greater vertical fault motion is likely to displace a greater amount of overlying water. Indeed, the Sumatra and Macquarie Ridge earthquakes occurred on different plate boundaries and had different faulting mechanisms. The Macquarie Ridge forms part of the Pacific-Australian plate boundary and the faulting mechanism of this earthquake is predominantly strike-slip. The Sumatra earthquake occurred on the interface of the India and Burma plates and its faulting mechanism was predominantly thrust with vertical slip.
		</p>

		<p>
			However, tsunamis can also arise from strike-slip earthquakes. A strike-slip Macquarie Ridge earthquake on May 1989, which had a similar magnitude (Mw 8.1) to the December 2004 earthquake, generated a small tsunami. A strike-slip earthquake in the Gulf of Alaska (November 1987, Mw 7.9) generated a 0.8 m tsunami while a strike-slip earthquake off the coast of northern California (Aug 1991, Mw 7.1) generated a 0.5 m tsunami. Although the fault displacements produced by these earthquakes were predominantly horizontal they may have had a slight vertical component. A combination of horizontal and vertical motion across a fault plane is called oblique slip. Strike-slip earthquakes can also cause underwater landslides that… ???
		</p>
	</li>

	<li>
		<p class="question">
			What other great (M > 8) earthquakes have occurred near Sumatra?
		</p>
		<p>
			Since 1900 and prior to the December 26 earthquake, the largest earthquake along the subduction zone from southern Sumatra to the Andaman Islands occurred in 2000 and had a magnitude of 7.9. A magnitude 8.4 earthquake occurred in 1797, a magnitude 8.5 in 1861 and a magnitude 8.7 in 1833 . All three ruptured sections of the subduction zone to the south of the recent earthquake. Interestingly, the 1797 and 1833 quakes are believed to have ruptured roughly the same area with only 36 years separating the events. Paleoseismic evidence shows that great earthquakes or earthquake couplets occur about every 230 years.
		</p>

		<p>
			Learn more: USGS Largest Earthquakes in the World Since 1900
		</p> <!--want a link-->
	</li>

	<li>
		<p class="question">
			What significant tsunamis prior to 2004 have occurred near Sumatra?
		</p>
		<p>
				<!--want as ordered list?-->
			<ol>
				 <li>1797: A magnitude 8.4 earthquake near the central part of the western Sumatra generated a tsunami that flooded Padang. More than 300 fatalities.</li>

				 <li>1833: A magnitude 8.7 earthquake near the south coast of the western Sumatra triggered a huge tsunami that flooded the southern part of western Sumatra. Numerous victims.</li>

				 <li>1843: A tsunami that came from the southeast and flooded the coast of the Nias Island. Many fatalities.</li>

				 <li>1861: A magnitude 8.5 earthquake affected all the western coast of Sumatra. Several thousand fatalities.</li>

				<li>1881: A magnitude 7.9 earthquake in the Andaman Island region generated a 1 m high tsunami on India's eastern coast.(1881 Earthquake: Geological Survey of India)</li>

				<li>1883: Krakatau explosion. 36,000 fatalities, primarily on the islands of Java and Sumatra.</li>

				<li>1941: A magnitude ~7.7 Adaman Islands earthquake. Anecdotal accounts exist of a tsunami, however, no official records exist.</li>
			</ol>
		</p>

		<p>
			Learn more:<br />
			<a href="http://tsun.sscc.ru/tsulab/20041226tsun.htm">Tsunami Laboratory, Institute of Computational Mathematics and Mathematical Geophysics</a><br />
			<a href="http://www.ngdc.noaa.gov/hazard/hazards.shtml">National Geophysical Data Center</a><br />
		</p>

	</li>

</ul>
