<?php
// Author: Lisa Wald
// Contact: Nick Beeler
// Last modified: Lisa Wald, 2016/08/10
  if (!isset($TEMPLATE)) {
  $TITLE = 'Rock Physics Labs';
  $NAVIGATION = true;
  $HEAD = '
    <link rel="stylesheet" href="../index.css"/>
  ';
    include 'template.inc.php';
  }
?>

<h2>Publications</h2>

<!--
 <ul class="topics"><li><a href="#" class="sel">All publications</a></li><li><a href="#strong">Friction - strong materials</a></li><li><a href="#weak">Friction - weak materials</a></li><li><a href="#fracture">Fracture and creep</a></li><li><a href="#acoustic">Acoustic emission</a></li><li><a href="#permeability">Permeability, resistivity, poroelasticity and wave speed</a></li><li><a href="#physics">Earthquake physics, modeling, and theory</a></li><li><a href="#fault">Fault zone studies</a></li></ul>  <div class="ten column">
 -->

<ul class="referencelist">
  <li class="strong physics"><a name="B" id="B"></a>Bartlow, N., Lockner, D., and Beeler, N., <a href="/static/lfs/research/rockphysics/Bartlow-Laboratory-triggering-of.pdf">Laboratory triggering of stick-slip events by oscillatory loading in the presence of pore fluid with implications for physics of tectonic tremor</a>, J. Geophy. Res., 117, B11411, 2012.</li>
  <li class="physics">Beeler, N., <a href="/static/lfs/research/rockphysics/Beeler-Constructing-constitutive-stre.pdf">Constructing constitutive relationships for seismic and aseismic fault slip</a>, Pure Appl. Geophy., 166, 1775-1798, 2009.</li>
  <li class="physics">Beeler, N. M., A. Thomas, R. B&uuml;rgmann, and D. Shelly, <a href="/static/lfs/research/rockphysics/Beeler-Inferring-fault-rheology-from-low-frequency-2013.pdf">Inferring fault rheology from low-frequency earthquakes on the San Andreas</a>,  J. Geophys. Res. Solid Earth, 118, 5976-5990, doi:10.1002/2013JB010118, 2013.</li>
  <li class="physics">Beeler, N. M., and S. H. Hickman, <a href="/static/lfs/research/rockphysics/Beeler-and-hickman-Direct-measurement-asperity-2015.pdf">Direct measurement of asperity contact growth in quartz at hydrothermal conditions</a>, J. Geophys. Res. Solid Earth, 120, doi: 10.1002/2014JB011816, 2015.</li>
  <li class="physics">Beeler, N. M., E. Roeloffs, and W. McCausland, <a href="/static/lfs/research/rockphysics/Beeler-Re-estimated-effects-deep-episodic-slip-2014.pdf">Re-estimated effects of deep episodic slip on the occurrence and probability of great earthquakes in Cascadia</a>, Bulletin of the Seismological Society of America, 104, 128-144, 2014.</li>
  <li class="physics">Beeler, N. M., T. Tullis, J. Junger, B. Kilgore, and D. Goldsby, <a href="/static/lfs/research/rockphysics/Beeler-Laboratory-constraints-models-of-earthquake-2014.pdf">Laboratory constraints on models of earthquake recurrence</a>, J. Geophys. Res. Solid Earth, 119, 8770-8791, doi:10.1002/2014JB011184, 2014.</li>
  <li class="physics strong">Beeler, N., Kilgore, B., McGarr, A., Fletcher, J., Evans, J., and Baker, S.R., <a href="http://ac.els-cdn.com/S019181411100201X/1-s2.0-S019181411100201X-main.pdf?_tid=932f9ef2-12ae-11e4-b8d2-00000aacb362&acdnat=1406150353_7059b24b7cc67575e933b2545912f012">Observed source parameters for dynamic rupture with non-uniform initial stress and relatively high fracture energy</a>, Structural Geology     DOI:10.1016/j.jsg.2011.11.013, 2012.</li>
  <li class="physics">Beeler, N.M., <a href="/static/lfs/research/rockphysics/Beeler-Inferring_earthquakes.pdf">Inferring earthquake source properties from laboratory observations and the scope of lab contributions to source physics, in Earthquakes: Radiated energy and earthquake physics</a>, eds. Abercrombie, McGarr, Kanamori, and Di Toro, Geophysical Monograph 170, 350 pp, 2006.</li>
  <li class="fracture physics weak">Beeler, N.M., <a href="/static/lfs/research/rockphysics/Beeler-Laboratory_faulting.pdf">Laboratory-observed faulting in intrinsically and apparently weak materials: strength, seismic coupling, dilatancy, and pore fluid pressure, in The Seismogenic Zone of Subduction Thrust Faults</a>, ed. T. Dixon and C. Moore, Columbia University Press, 2007.</li>
  <li class="fracture physics">Beeler, N.M., <a href="/static/lfs/research/rockphysics/Beeler-Brittle_failure.pdf">Review of the physical basis of laboratory-derived relations for brittle failure and their implications for earthquake occurrence and earthquake nucleation</a>, Pure App. Geophy., 161, 1853-1876, 2004.</li>
  <li class="physics">Beeler, N.M., and D.A. Lockner, <a href="/static/lfs/research/rockphysics/nmb_2001JB001518.pdf">Why earthquakes correlate weakly with the solid Earth tides: Effects of periodic stress on the rate and probability of earthquakes</a>, J. Geophys. Res., 108 (B8), doi: 10.1029/2001JB001518, 2003.</li>
  <li class="fracture physics">Beeler, N.M., and Hickman, S.H., <a href="/static/lfs/research/rockphysics/Beeler-Fracture_closure.pdf">Stress-induced, time-dependent fracture closure at hydrothermal conditions</a>, J. Geophy. Res., 109, doi:10.1029/2002JB001782, 2004.</li>
  <li class="strong fracture physics">Beeler, N.M., Lockner, D.L., and Hickman, S.H., <a href="/static/lfs/research/rockphysics/Beeler-Simple_stick-slip.pdf">A simple stick-slip and creep-slip model for repeating earthquakes and its implication for microearthquakes at Parkfield</a>, Bull. Seis. Soc. Am., 91(6), 1797-1804, 2001.</li>
  <li class="strong weak">Beeler, N.M., T.E. Tullis, A. K. Kronenberg, and  Reinen , L.A., <a href="/static/lfs/research/rockphysics/Beeler-Instantaneous.pdf">The instantaneous rate dependence in low temperature laboratory rock friction and rock deformation experiments</a>, J. Geophys. Res., 112, B07310, doi:10.1029/2005JB003772, 2007.</li>
  <li class="physics weak">Beeler, N.M., T.E. Tullis, and D. L Goldsby, <a href="/static/lfs/research/rockphysics/Beeler-Constitutive_relationships.pdf">Constitutive relationships and physical basis of fault strength due to flash-heating</a>, J. Geophys. Res., 113, B01401, doi:10.1029/2007JB00498, 2008.</li>
  <li class="physics">Beeler, N.M., Wong, T.-f., and Hickman, S.H., <a href="/static/lfs/research/rockphysics/Beeler-Expected_relationships.pdf">On expected relationships between apparent stress, static stress drop, effective shear fracture energy, and efficiency</a>, Bull. Seis. Soc. Am., 93, 1381-1389, 2003.</li>
  <li class="strong">Blanpied, M., Lockner, D., and Byerlee, J., <a href="/static/lfs/research/rockphysics/Blanpied-Frictional-slip-of-granite-at.pdf">Frictional slip of granite at hydrothermal conditions</a>, J. Geophy. Res., 100 (B7), 13045-133064, 1995.</li>
  <li class="strong fault">Boulton, C., Moore, D., Lockner, D., Toy, V., Townsend, J., and Sutherland, R., <a href="/static/lfs/research/rockphysics/Boulton_AlpineFlt_GRL2014.pdf">Frictional properties of exhumed fault gouges in DFDP-1 core, Alpine fault, New Zealand</a>, Geopys. Res. Lett., 41, doi:10.1002/2013GL058236, 2014.</li>
  <li class="strong">Byerlee, J., <a href="/static/lfs/research/rockphysics/Friction_of_rocks.pdf">Friction of rocks</a>, Pure App. Geophy., 166, 615-625, 1978.</li>
  <li class="strong">Byerlee, J., <a href="/static/lfs/research/rockphysics/Byerlee-Friction-overpressure-fault.pdf">Friction, overpressure and fault normal compression</a>, Geophy. Res. Lett., 17, (12), 2109-2112, 1990.</li>
  <li class="acoustic">Byerlee, J.D., and Lockner, D.A., <a href="/static/lfs/research/rockphysics/Byerlee_Lockner-AE--during-fluid-injection-1st-Conf-1977.pdf">Acoustic emission during fluid injection in rock, in Proceedings, First Conference on Acoustic Emission/Microseismic Activity in Geological Structures and Materials</a>, edited by H. R. Hardy and F. W. Leighton, pp. 87-98, Trans Tech Publications, Clausthal-Z, Germany, 1977.</li>
  <li class="strong physics"><a name="C" id="C"></a>Chang, J., Lockner, D., and Reches, Z., <a href="/static/lfs/research/rockphysics/Chang-Rapid-weakening-ELSE_Science_2012.pdf">Rapid acceleration leads to rapid weakening in earthquake-like laboratory experiments</a>, Science, 338, 101-104, 2012.</li>
  <li class="strong"><a name="D" id="D"></a>Dieterich, J.H., and Kilgore, B.D., <a href="/static/lfs/research/rockphysics/Observation_contacts.pdf">Direct observation of frictional contacts: New insights for state-dependent properties</a>, PAGEOPH, 143, no. 1/2/3, 283-302, 1994.</li>
  <li class="strong">Dieterich, J.H., and Kilgore, B.D., <a href="/static/lfs/research/rockphysics/Imaging_surface_contacts.pdf">Imaging surface contacts: power law contact distributions and stresses in quartz, calcite, glass and acrylic plastic</a>, Tectonophysics, 256, 219-239, 1996.</li>
  <li class="weak physics">Dieterich, J.H., and Kilgore, B.D., <a href="/static/lfs/research/rockphysics/prediction.pdf">Implications of fault constitutive properties for earthquake prediction</a>, Proc. Natl. Acad. Sci. USA, 93, 3787-3794, 1996.</li>
  <li><a name="F" id="F"></a>Farough, A., Moore, D.E., Lockner, D.A., and Lowell, R.P, <a href="/static/lfs/research/rockphysics/Farough_et_al_2016.pdf">Evolution of fracture permeability of ultramafic rocks undergoing serpentinization at hydrothermal conditions: An experimental study</a>, Geochemistry, Geophysics, Geosystems, 17, 44-55, 2016, doi:10.1002/2015GC005973.</li>
  <li class="physics"><a name="H" id="H"></a>He, C., Wong, T.-f., and Beeler, N., <a href="/static/lfs/research/rockphysics/He-Wong-Beeler-Stress-drop-Fault-strength2003.pdf">Scaling of stress drop with recurrence interval and loading velocity for laboratory-derived fault strength relations</a>, J., Geophy., Res., 108, 2037, 2003.</li>
  <li class="physics">Hirth, G. and N. M. Beeler, <a href="/static/lfs/research/rockphysics/Hirth-and-Beeler-Role-of-fluid-pressure-on-frictional-2015.pdf">The role of fluid pressure on frictional behavior at the base of the seismogenic zone</a>, Geology, 43, 3, 223-226, doi:10.1130/G36361.1, 2015.</li>
  <li class="strong"><a name="K" id="K"></a>Kilgore, B., Lozos, J., Beeler, N., and Oglesby, D., <a href="/static/lfs/research/rockphysics/Kilgore-et-al-2012-Journal-of-Applied-Mechanics.pdf">Laboratory observations of fault strength in response to changes in normal stress</a>,  J. App. Mechanics, 79, 031007-1, 2012.</li>
  <li>Kilgore, B., McGarr, A., Beeler, N., and Lockner, D., <a href="/static/lfs/research/rockphysics/Kilgore-et-al-2017-AGU-Monograph.pdf">Earthquake source properties from instrumented stick-slip, In &ldquo;Fault zone dynamic processes: Evolution of fault properties during seismic rupture&rdquo;</a>, Geophysical Monograph 227 (eds. Thomas, M., Bhat, H. S., and Mitchell, T.) Am. Geophys. Union and John Wiley &amp; Sons, Washington, D.C. and Hoboken, ISBN: 978-1-119-15688-8, 2017.</li>
  <li>Kilgore, B., N. M. Beeler, J. Lozos, and D. Oglesby, <a href="/static/lfs/research/rockphysics/Kilgore-2017-JGR-Rock-friction-under-variable-normal-stress.pdf">Rock friction under variable normal stress</a>, J. Geophys. Res. Solid Earth, 122, doi:10.1002/2017JB014049, 2017.</li>
  <li class="strong">Kilgore, B.D., Blanpied, M. L., and Dietrich, J. H., <a href="/static/lfs/research/rockphysics/Kilgore-Blanpied-Dieterich-1993-Velocity-dependent-friction-of-granite.pdf">Velocity-dependent Friction of Granite over a Wide Range of Conditions</a>, Geophys. Res. Lett. 20, 903-906, DOI:10.1029/93GL00368, 1993.</li>
  <li class="permeability"><a name="L" id="L"></a>Lindh, A., Lockner, D.,  and Lee, W., <a href="/static/lfs/research/rockphysics/Lindh-etal-BSSA-1978-Velocity-anomalies.pdf">Velocity anomalies: an alternative explanation</a>, Bull. of the Seism. Soc. of Amer., 68(3), 721-734, 1978.</li>
  <li class="fracture acoustic">Lockner, D., and Byerlee, J., <a href="/static/lfs/research/rockphysics/Lockner_Byerlee-AE-and-Faults-1st-Conf-1977.pdf">Acoustic emission and fault formation in rocks</a>, in Proceedings, First Conference on Acoustic Emission/Microseismic Activity in Geological Structures and Materials, edited by H. R. Hardy and W. F. Leighton, pp. 99-107, Trans Tech Publications, Clausthal-Zellerfeld, Germany, 1977.</li>
  <li class="permeability">Lockner, D., and Evans, B., <a href="/static/lfs/research/rockphysics/Lockner_Evans-Densification-of-qtz-JGR-1995.pdf">Densification of quartz powder and reduction of conductivity at 700&deg;C</a>, J. Geophys. Res., 100(B7), 13,081-013,092, 1995.</li>
  <li class="fracture acoustic">Lockner, D., Byerlee, J., Kuksenko, V., Ponomarev, A., and Sidorin, A., <a href="/static/lfs/research/rockphysics/Lockner_etal_Nature1991_Quasistatic_fault_growth.pdf">Quasi-static fault growth and shear fracture energy in granite</a>, Nature, 350(6313) 39-42, 1991.</li>
  <li class="physics">Lockner, D., Johnson, M., and Byerlee, J., <a href="/static/lfs/research/rockphysics/Lockner_etal_Nature1983_EQLights.pdf">A mechanism to explain the generation of earthquake lights</a>, Nature, 302(5903), 28-33, 1983.</li>
  <li class="fracture">Lockner, D.A., <a href="/static/lfs/research/rockphysics/Lockner_GenLaw_jgr98.pdf">A generalized law for brittle deformation of Westerly granite</a>, J. Geophys. Res., 103, 5107-5123, 1998.</li>
  <li class="fracture acoustic">Lockner, D.A., <a href="/static/lfs/research/rockphysics/RoleofAE_Lockner1993.pdf">The role of acoustic emission in the study of rock fracture</a>, Int. J. Rock Mech. Min. Sci. Geomech. Abstr., 30, 883-899, 1993.</li>
  <li class="physics">Lockner, D.A., and Beeler, N.M., <a href="/static/lfs/research/rockphysics/LocknerTdlTrigJGR99.pdf">Premonitory slip and tidal triggering of earthquakes</a>, J. Geophys. Res., 104, 20133-120151, 1999.</li>
  <li class="fracture physics">Lockner, D.A., and Beeler, N.M., <a href="/static/lfs/research/rockphysics/IASPEI-Chap32-RockFailure.pdf">Rock Failure and Earthquakes - Chapter 32</a>, International Handbook of Earthquake and Engineering Seismology, edited by W.H.K. Lee, H. Kanamori, P.C. Jennings, and C. Kisslinger, pp. 505-537 (plus appendix on CD-ROM), Academic Press, Amsterdam, 2002.</li>
  <li class="permeability">Lockner, D.A., and Beeler, N.M., <a href="/static/lfs/research/rockphysics/Lockner_ASCE2003.pdf">Stress-induced anisotropic poroelasticity response in sandstone</a>, Electronic Proc. 16th ASCE Engin. Mech. Conf., U. Washington, Seattle, WA, July 16-18, 2003.</li>
  <li class="fracture acoustic">Lockner, D.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Lockner_Byerlee_BSSA1977_AEandCreep.pdf">Acoustic emission and creep in rock at high confining pressure and differential stress</a>, Bull. of the Seismological Society of Amer., 67, 247-258, 1977.</li>
  <li class="fracture permeability">Lockner, D.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/CmplxRes_Lockner1986.pdf">Changes in complex resistivity during creep in granite</a>, Pure and Appl. Geophys., 124, 659-676, 1986.</li>
  <li class="permeability">Lockner, D.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Lockner_Byerlee-Complex-Resistivity-JGR-1985.pdf">Complex resistivity measurements of confined rocks</a>, J. Geophys. Res., 90, 7837-7847, 1985.</li>
  <li class="permeability">Lockner, D.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Lockner_Byerlee-Complex-resistivity-GRL-1985.pdf">Complex resistivity of fault gouge and its significance for earthquake lights and induced polarization</a>, Geophys. Res. Lett., 12, 211-214, 1985.</li>
  <li class="fracture acoustic">Lockner, D.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Lockner_Byerlee-Development-of-fracture-2nd-Conf-1980.pdf">Development of fracture planes during creep in granite</a>, in Proceedings, Second Conference on Acoustic Emission/Microseismic Activity in Geological Structures and Materials, edited by H. R. Hardy and W. F. Leighton, pp. 11-25, Trans-Tech Publications, Clausthal-Zellerfeld, Germany, 1980.</li>
  <li class="fracture acoustic">Lockner, D.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Lockner_Byerlee_Fault-Growth-AMR-1992.pdf">Fault growth and acoustic emissions in confined granite</a>, J. Appl. Mech. Rev., 45(3), S165-S173, 1992.</li>
  <li class="fracture acoustic">Lockner, D.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Lockner_hydrofrac_JGR77.pdf">Hydrofracture in Weber sandstone at high confining pressure and differential stress</a>, J. Geophys. Res., 82, 2018-2026, 1977b.</li>
  <li class="fracture acoustic">Lockner, D.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Lockner_Byerlee-Precursory-AE-Patterns-5th-Conf-1995.pdf">Precursory AE patterns leading to rock fracture, in Proceedings, Fifth Conference on Acoustic Emission/Microseismic Activity in Geological Structures and Materials</a>, edited by H. R. Hardy, pp. 45-58, Trans Tech Publications, Clausthal-Zellerfeld, Germany, 1995.</li>
  <li class="strong physics">Lockner, D.A., and Okubo, P.G., <a href="/static/lfs/research/rockphysics/Lockner_Heat_jgr83.pdf">Measurements of frictional heating in granite</a>, J. Geophys. Res., 88, 4313-4320, 1983.</li>
  <li class="permeability">Lockner, D.A., and Stanchits S.A., <a href="/static/lfs/research/rockphysics/dal_JGR2001jb001460.pdf">Undrained poroelastic response of sandstones to deviatoric stress change</a>, J. Geophys. Res., 107 (B12), 2353, doi:10.1029/2001JB001460, 2002.</li>
  <li class="fracture acoustic">Lockner, D.A., Byerlee, J.D., Kuksenko, V., Ponomarev, A., and Sidorin, A., <a href="/static/lfs/research/rockphysics/quasistatic_growth.pdf">Observation of quasistatic fault growth from acoustic emissions</a>, Fault Mechanics and Transport Properties of Rocks, Academic Press, Ltd., 1992.</li>
  <li class="strong permeability">Lockner, D.A., Byerlee, J.D., Kuksenko, V.S., and Ponomarev, A.V., <a href="/static/lfs/research/rockphysics/Lockner-etal-PAGEOPH-1986-Stick-slip-charge-separation.pdf">Stick slip, charge separation and decay</a>, Pure and Appl. Geophys., 124, 601-608, 1986.</li>
  <li class="strong permeability fault">Lockner, D.A., H. Tanaka, H. Ito, R. Ikeda, K. Omura, and H. Naka, <a href="/static/lfs/research/rockphysics/LocknerPAGEOPH2009_Nojima.pdf">Geometry of the Nojima fault at Nojima-Hirabayashi, Japan - I. A simple damage structure inferred from borehole core permeability</a>, Pure Appl. Geophys., 166, doi 10.1007/s00024-00009-00515-00020, 2009.</li>
  <li class="permeability">Lockner, D.A., Hickman, S., Byerlee, J.D., Kuksenko, V., Ponomarev, A., Sidorin, A., and Khakaev, B., <a href="/static/lfs/research/rockphysics/Lockner-etal-GRL-1991-Laboratory-determined-perm-from-KOLA.pdf">Laboratory-determined permeability of cores from the Kola superdeep well, USSR</a>, Geophys. Res. Lett., 18(5), 881-884, doi:10.1029/91GL00782, 1991.</li>
  <li class="weak fault">Lockner, D.A., Morrow, C.A., Moore, D.E., and Hickman, S.H., <a href="/static/lfs/research/rockphysics/Lockner-SAFOD-2011.pdf">Low strength of deep San Andreas fault gouge from SAFOD core</a>, Nature, doi:10.1038/nature09927, 2011.</li>
  <li class="strong permeability fault">Lockner, D.A., Naka, H., Tanaka, H., Ito, H., and Ikeda, R., <a href="/static/lfs/research/rockphysics/Permeability_strength.pdf">Permeability and strength of core samples from the Nojima fault of the 1995 Kobe earthquake</a>, Proceedings, International Workshop on the Nojima Fault Core and Borehole Data Analysis, Nov. 22-23, 1999, Tsukuba, Japan, edited by H. Ito, K. Fujimoto, H. Tanaka and D. Lockner, 2000.</li>
  <li class="permeability">Lockner, D.A., Walsh, J.B., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Lockner_VelAttn_JGR77.pdf">Changes in seismic velocity and attenuation during deformation of granite</a>, J. Geophys. Res., 82, 5374-5378, 1977.</li>
  <li class="acoustic"><a name="M" id="M"></a>McLaskey, G. C., and D. A. Lockner, <a href="/static/lfs/research/rockphysics/McLaskey-Calibrated-acoustic-emmission-system-2015.pdf">Calibrated acoustic emission system records M -3.5 to M -8 events generated on a saw-cut granite sample</a>, Am. Rock Mech. Ass. 15-204, 2015.</li>
  <li class="strong">McLaskey, G. C., and D. A. Lockner, <a href="/static/lfs/research/rockphysics/McLaskey-Preslip-and-cascade-processes-initiating-laboratory-2014.pdf">Preslip and cascade processes initiating laboratory stick slip</a>, J. Geophys. Res. Solid Earth, 119, 6323-6336, doi:10.1002/2014JB011220, 2014.</li>
  <li class="strong">McLaskey, G. C., B. D. Kilgore, and N. M. Beeler, <a href="/static/lfs/research/rockphysics/McLaskey-Slip-Pulse-rupture-behavior-on-2m-granite-fault-2015.pdf">Slip-pulse rupture behavior on a 2 m granite fault</a>, Geophys. Res. Lett., 42, doi:10.1002/2015GL065207, 2015.</li>
  <li class="acoustic">McLaskey, G. C., D. A. Lockner, B. D. Kilgore, and N. M. Beeler, <a href="/static/lfs/research/rockphysics/McLaskey-A-robust-calibration-technique-for-AE-2015.pdf">A Robust Calibration Technique for Acoustic Emission Systems Based on Momentum Transfer from a Ball Drop</a>, Bulletin of the Seismological Society of America, 105(1), 257-271, doi: 10.1785/0120, 2015.</li>
  <li class="strong fracture physics">McLaskey, G.,  and Kilgore, B., <a href="http://onlinelibrary.wiley.com/store/10.1002/jgrb.50232/asset/jgrb50232.pdf?v=1&t=hxz5gaaa&s=0dcd9776e296afc97b22d11f22e2eb6f6a64e312">Foreshocks during the nucleation of stick-slip instability</a>, J. Geophy. Res., 118, 2982-2997, doi:10.1002/jgrb.50232, 2013.</li>
  <li class="acoustic physics">McLaskey, G., Kilgore, B., Lockner, D., and Beeler, N., <a href="http://download.springer.com/static/pdf/76/art%253A10.1007%252Fs00024-013-0772-9.pdf?auth66=1406322391_50f2b4ea56fca9ad79dda5e023994a13&ext=.pdf">Laboratory generated M-6 earthquakes</a>, Pure Appl. Geopys., doi: 10.1007/s00024-013-0772-9, 2014.</li>
  <li class="fault">Moore, D., <a href="/static/lfs/research/rockphysics/Moore-Comparative-mineral-chemistry-JSG-2014.pdf">Comparative mineral chemistry and textures of SAFOD fault gouge and damage-zone rocks</a>, J. Struc. Geo., 68, 82-96, 2015.</li>
  <li class="fault">Moore, D., and Byerlee, J., <a href="/static/lfs/research/rockphysics/comparative-geometry-of-the-San-andreas-.pdf">Comparative geometry of the San Andreas fault, California, and laboratory fault zones</a>, Bull. Geol. Soc. Am., 103, 762-744, 1991.</li>
  <li class="fault">Moore, D., and Byerlee, J., <a href="/static/lfs/research/rockphysics/relationships-between-sliding-behavior-and-internal.pdf">Relationships between sliding behavior and internal geometry of laboratory fault zones and some creeping and locked strike-slip faults of California</a>, Tectonophysics, 211, 305-316, 1992.</li>
  <li class="strong weak">Moore, D., and Byerlee, J., <a href="/static/lfs/research/rockphysics/textural-development-of-clayey-and-quartzofeld.pdf">Textural development of clayey and quartzofeldspathic fault gouges relative to their sliding behavior</a>, Phys. Chem. Earth, 17, 1-9, 1989.</li>
  <li class="weak">Moore, D., and Lockner, D., <a href="/static/lfs/research/rockphysics/Moore-Chemical-controls-on-fault.pdf">Chemical controls on fault behavior: Weakening of serpentinite sheared against quartz-bearing rocks and its significance for fault creep in the San Andreas system</a>, J. Geophy. Res., 118, 1-13, doi:10.1002/jgrb.50140, 2013.</li>
  <li class="weak">Moore, D., and Lockner, D. , <a href="/static/lfs/research/rockphysics/crystallographic-controls-on-the-frictional-behave.pdf">Crystallographic controls on the frictional behavior of dry and water-saturated sheet structure minerals</a>, J. Geophys. Res., 109, B03401, 2004.</li>
  <li class="weak">Moore, D., and Lockner, D., <a href="/static/lfs/research/rockphysics/Moore-Frictional-strengths-of-talc-se.pdf">Frictional strengths of talc-serpentine and talc-quartz mixtures</a>, J. Geophy. Res., 116, B01403, doi:10.1029/2010JB007881, 2011.</li>
  <li class="fracture">Moore, D., and Lockner, D., <a href="/static/lfs/research/rockphysics/Moore-Role-of-microcracking-in-shear.pdf">The role of microcracking in shear-fracture propagation in granite</a>, J. Structural Geology, 17(1), 95-114, 1995.</li>
  <li class="weak fault">Moore, D., and Rymer, M., <a href="/static/lfs/research/rockphysics/Moore-Correlation-of-clayey-gouge.pdf">Correlation of clayey gouge in a surface exposure of serpentinite in the San Andreas Fault with gouge from the San Andreas Fault Observatory at Depth (SAFOD)</a>, J. Structural Geology, 38, 51-60, 2012.</li>
  <li class="weak">Moore, D., and Rymer, M. , <a href="/static/lfs/research/rockphysics/talc-bearing-serpentinite-and-the-creeping-section.pdf">Talc-bearing serpentinite and the creeping section of the San Andreas fault</a>, Nature, 448, doi:10.1038/nature06064, 2007.</li>
  <li>Moore, D.E., Lockner, D.A., and Hickman, S., <a href="/static/lfs/research/rockphysics/Mooreetal_2016_SAFOD.pdf">Hydrothermal frictional strengths of rock and mineral samples relevant to the creeping section of the San Andreas Fault</a>, Journal of Structural Geology, 89, 153-167, 2016, doi:10.1016/j.jsg.2016.06.005.</li>
  <li>Moore, D.E., Lockner, D.A., Kilgore, B.D., and Beeler, N.M., <a href="http://dx.doi.org/10.3133/ofr20161059">Gallery of melt textures developed in Westerly granite during high-pressure triaxial friction experiments</a>, U. S. Geological Survey Open-File Report, 2016-1059, 75 p., 2016.</li>
  <li class="permeability">Moore, D.E., Morrow, C.A., and Byerlee, J.D. , <a href="/static/lfs/research/rockphysics/Hi-temp-permeability-and-groundwater-chem.pdf">High-temperature permeability and groundwater chemistry of some Nevada Test Site Tuffs</a>, Journal of Geophysical Research, 91(B2), 2163-2171, 1986.</li>
  <li class="fault">Moore, D., Hickman, S., Lockner, D., and Dobson, P. , <a href="/static/lfs/research/rockphysics/hydrothermal-minerals-and-microstructures.pdf">Hydrothermal minerals and microstructures in the Silangkitang geothermal field along the Great Sumatra fault zone, Sumatra, Indonesia</a>, Bull. Geol. Soc. Am., 113, 1179-1192, 2001.</li>
  <li class="weak">Moore, D., Lockner, D., Shengli, M., Summers, R., Byerlee, J., <a href="/static/lfs/research/rockphysics/Moore-Strengths-Serpentinite-gouge.pdf">Strengths of serpentinite gouges at elevated temperatures</a>, J. Geophy. Res., 102(B7), 14787-14801, 1997.</li>
  <li class="weak">Moore, D., Lockner, D., Summers, R., Shengli, M., and Byerlee, J., <a href="/static/lfs/research/rockphysics/Moore-StrengthofChrysotile-Geol-1996.pdf">Strength of chrysotile-serpentinite gouge under hydrothermal conditions: Can it explain a weak San Andreas fault?</a>, Geology, 24(11), 1041-1044, 1996.</li>
  <li class="weak">Moore, D., Lockner, D., Tanaka, H., Iwata, K., <a href="/static/lfs/research/rockphysics/Moore-coefficient-of-fric-chrysotile2004.pdf">The coefficient of friction of chrysotile gouge at seismogenic depths</a>, Int. Geology Review, 1-14, 2004.</li>
  <li class="weak">Moore, D., Ma, J., Summers, R, and Byerlee, J., <a href="/static/lfs/research/rockphysics/effect-of-pore-pressure-and-heating-time.pdf">The effect of pore pressure and heating time on the strength and sliding stability of a serpentinite gouge</a>, in Proc. 25th Symp. Rock Mech., 312-319, 1984.</li>
  <li class="strong">Moore, D., Summers, R., and Byerlee, J., <a href="/static/lfs/research/rockphysics/deformation-of-granite-during-triaxial.pdf">Deformation of granite during triaxial friction tests, in Mechanics of Jointed and Faulted Rock, H. Rossmanith, ed.</a>, Proc. Int. Conf. Mechanics of Jointed Rock, Vienna, 1990.</li>
  <li class="strong">Moore, D., Summers, R., and Byerlee, J. , <a href="/static/lfs/research/rockphysics/relationship-between-textures-and-sliding-motion.pdf">Relationship between textures and sliding motion of experimentally deformed fault gouge: Application to fault zone behavior, in Key Questions in Rock Mechanics</a>, Proc. 29th Symp., Cundall, Sterling and Starfield, ed, 1988.</li>
  <li class="weak">Moore, D., Summers, R., and Byerlee, J. , <a href="/static/lfs/research/rockphysics/sliding-behavior-and-deformation-textures-of-illite.pdf">Sliding behavior and deformation textures of heated illite gouge</a>, J. Structural Geol., 11, 329-342, 1989.</li>
  <li class="weak">Moore, D., Summers, R., and Byerlee, J., <a href="/static/lfs/research/rockphysics/strengths-of-clay-and-non-clay-fault-gouges.pdf">Strengths of clay and non-clay fault gouges at elevated temperatures and pressures</a>, 24th Symp. on Rock Mech., C. Mathewson, ed., 489-500, 1983.</li>
  <li class="strong">Moore, D., Summers, R., and Byerlee, J. , <a href="/static/lfs/research/rockphysics/effects-of-sliding-velocity-on-the-frictional.pdf">The effects of sliding velocity on the frictional and physical properties of heated fault gouge</a>, Pure Appl. Geophy, 124(1/2), 1986.</li>
  <li class="weak">Moore, D.E., and Lockner, D.A., <a href="/static/lfs/research/rockphysics/IGR2007.pdf">Comparative deformation behavior of minerals in serpentinized ultramafic rock: Application to the slab-mantle interface in subduction zones</a>, International Geology Review, 49, 401-415, 2007.</li>
  <li class="weak">Moore, D.E., and Lockner, D.A., <a href="/static/lfs/research/rockphysics/Moore-Crystallographic_controls.pdf">Crystallographic controls on the frictional strengths of layered-structured minerals</a>, (poster), 2004.</li>
  <li class="weak">Moore, D.E., and Lockner, D.A., <a href="/static/lfs/research/rockphysics/MooreLocknerCh11.pdf">Friction of the smectite clay montmorillonite: A review and interpretation of data, in The Seismogenic Zone of Subduction Thrust Faults</a>, T. H. Dixon and C. Moore, eds., Margins Theoretical and Experimental Earth Science Series, vol. 2, Columbia University Press, pp. 317-345, 2007.</li>
  <li class="weak">Moore, D.E., and Lockner, D.A., <a href="/static/lfs/research/rockphysics/Moore-Frictional_behavior.pdf">Interpreting the frictional behavior of the smectite clay montmorillonite</a>, American Geophysical Union (poster), 2004.</li>
  <li class="weak">Moore, D.E., and Lockner, D.A., <a href="/static/lfs/research/rockphysics/Moore-Solution_transfer_processes.pdf">Solid solution processes and the frictional strength of heated brucite</a>, American Geophysical Union (poster), 2005.</li>
  <li class="weak">Moore, D.E., and Lockner, D.A., <a href="/static/lfs/research/rockphysics/Tectonophysics2008.pdf">Talc friction in the temperature range 25&deg;-400&deg;C: Relevance for fault-zone weakening</a>, Tectonophysics, 449, 120-132, 2008.</li>
  <li class="strong permeability fault">Moore, D.E., D.A. Lockner, H. Ito, R. Ikeda, H. Tanaka, and K. Omura, <a href="/static/lfs/research/rockphysics/MoorePAGEOPH2009_Nojima.pdf">Geometry of the Nojima fault at Nojima-Hirabayashi, Japan - II. Microstructures and their implications for permeability and strength</a>, Pure Appl. Geophys., 166, doi 10.1007/s00024-00009-00513-00022, 2009.</li>
  <li class="permeability">Moore, D.E., Lockner, D.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Moore-etal-Reduction-of-permeability-Science-1994.pdf">Reduction of permeability in granite at elevated temperatures</a>, Science, 265, 1558-1561, doi:10.1126/science.265.5178.1558, 1994.</li>
  <li class="weak">Moore, D.E., Lockner, D.A., and Ponce, D.A., <a href="/static/lfs/research/rockphysics/Hayward_MS_Moore.pdf">Anomalously low strength of serpentine sheared against granite and implications for creep on the Hayward and Calaveras faults</a>, Proceedings, 3rd Conference on earthquake hazards in the eastern San Francisco Bay Area: Science, Hazard, Engineering and Risk, edited by K. Knudsen and others, Oct. 22-24, 2008 Cal. State U. East Bay, 2010.</li>
  <li class="strong permeability fault">Moore, D.E., Lockner, D.A., Ito, H. and Ikeda, R., <a href="/static/lfs/research/rockphysics/ExtAbsform.pdf">Correlation of Deformation Textures with Laboratory Measurements of Permeability and Strength of Nojima Fault Zone Core Samples</a>, Proceedings, International Workshop on the Nojima Fault Core and Borehole Data Analysis, Nov. 22-23, 1999, Tsukuba, Japan, edited by H. Ito, K. Fujimoto, H. Tanaka and D. Lockner, 2000.</li>
  <li class="weak">Moore, D.E., Lockner, D.A., Tanaka, H., and Iwata, K., <a href="/static/lfs/research/rockphysics/chrysotile2004.pdf">The coefficient of friction of chrysotile gouge at seismogenic depths</a>, International Geology Review, 16, 385-398. (Republished in the collection, W. G. Ernst, ed., 2004, Serpentine and Serpentinites: Mineralogy, Petrology, Geochemistry, Ecology, Geophysics, and Tectonics: Geological Society of America International Book Seri, 2004.</li>
  <li class="permeability">Moore, D.E., Morrow, C.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/chem-reactions-accompanying-fluid-flow.pdf">Chemical reactions accompanying fluid flow through granite held in a temperature gradient</a>, Geochemica et Cosmochemica Acta, 47, 445, 1983.</li>
  <li class="permeability">Moore, D.E., Morrow, C.A., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/use-of-swelling-clays-to-reduce-permeability.pdf">Use of swelling clays to reduce permeability in fractured rock</a>, Geophysical Research Letters, 9(9), 1009-1012, 1982.</li>
  <li class="weak fault">Moore, D.E., Rymer, M.J., McLaughlin, R.J., and Lienkaemper, J.J., <a href="/static/lfs/research/rockphysics/Moore-AGU-2011.pdf">Mineralogy of faults in the San Andreas system that are characterized by creep</a>, EOS, Tran. Am. Geophy. Un., Fall Meeting (poster), 2011.</li>
  <li class="permeability">Morrow, C. and Byerlee, J.D. , <a href="/static/lfs/research/rockphysics/permeability-of-rock-samples-from-Cajon-Pass.pdf">Permeability of rock samples from Cajon Pass, California</a>, Geophysical Research Letters, 15(9), 1033-1036, 1988.</li>
  <li class="strong">Morrow, C., and Byerlee, J. , <a href="/static/lfs/research/rockphysics/experimental-studies-compaction-and-dilatancy.pdf">Experimental studies of compaction and dilatancy during frictional sliding on faults containing gouge</a>, Journal of Structural Geology, 11(7), 815-825, 1989.</li>
  <li class="strong fracture">Morrow, C., and Byerlee, J., <a href="/static/lfs/research/rockphysics/fric-sliding-and-fracture-Nevada-test-site.pdf">Frictional sliding and fracture behavior of some Nevada Test Site Tuffs, Rock mechanics in productivity and protection</a>, Proceedings 25th Symposium on Rock Mechanics, Dowding and Singh, eds., 467-474, 1984.</li>
  <li class="permeability">Morrow, C., and Byerlee, J. , <a href="/static/lfs/research/rockphysics/perm-of-core-samples-from-cajon-scientific-drill.pdf">Permeability of core samples from Cajon Pass Scientific Drillhole:  Results from 2100 to 3500 m depth</a>, Journal of Geophysical Research, 97(B4), 5145-5151, 1992.</li>
  <li class="fracture">Morrow, C., Lockner, D., and Okubo, C., <a href="/static/lfs/research/rockphysics/Morrow-Mechanical-properties-Mars-OFR-2013.pdf">Mechanical properties of simulated Mars materials- gypsum-rich sandstones and lapilli tuff</a>, U.S. Geological Survey Open-File Report, 2013-1242, 2013.</li>
  <li>Morrow, C., Lockner, D.A., and Hickman, S., <a href="/static/lfs/research/rockphysics/Morrow resistivity 2015.pdf">Low resistivity and permeability in actively deforming shear zones on the San Andreas Fault at SAFOD</a>, Journal of Geophysical Research, 120(12), 8240-8258, 2015, doi:10.1002/2015JB012214.</li>
  <li class="permeability">Morrow, C., Lockner, D., Hickman, S., Rusanov, B., and R&ouml;ckel, T. , <a href="/static/lfs/research/rockphysics/effects-of-lithology-and-depth-on-the-permeability.pdf">Effects of lithology and depth on the permeability of core samples from the Kola and KTB drillholes</a>, Journal of Geophysical Research, 99(B4), 7263-7274, 1994.</li>
  <li class="permeability">Morrow, C., Lockner, D., Moore, D., and Byerlee, J., <a href="/static/lfs/research/rockphysics/Morrow-etal-JGR-1981-Perm-of-granite-in-temp-gradient.pdf">Permeability of granite in a temperature gradient</a>, J. Geophys. Res., 86, 3002-3008, doi:10.1029/JB086iB04p03002, 1981.</li>
  <li class="permeability fault">Morrow, C., Lockner, D., Moore, D., and Hickman, S., <a href="/static/lfs/research/rockphysics/Morrow-SAFOD-Perm-JSG2013-SG2964.pdf">Deep permeability of the San Andreas fault from San Andreas Fault at Depth (SAFOD) core samples</a>,  J. Struc. Geo., http://dx.doi.org/10.1016/j.jsg.2013.09.009, 2013.</li>
  <li class="permeability">Morrow, C., Moore, D., and Byerlee, J. , <a href="/static/lfs/research/rockphysics/perm-and-pore-fluid-chemistry-bullfrog-tuff.pdf">Permeability and pore fluid chemistry of the Bullfrog Tuff in a temperature gradient</a>, Proceedings, 24th U.S. Symposium on Rock Mechanics, C. Mathewson, ed., 819-828, 1983.</li>
  <li class="permeability">Morrow, C., Moore, D., and Byerlee, J., <a href="/static/lfs/research/rockphysics/perm-changes-in-crystalline-rocks-due-to-temp.pdf">Permeability changes in crystalline rocks due to temperature: Effects of mineral assemblage</a>, Materials Research Society Proceedings, 44, 467-474, 1985.</li>
  <li class="permeability">Morrow, C., Zhang Bo-Chong, and Byerlee, J. , <a href="/static/lfs/research/rockphysics/effective-pressure-law-for-permeability-of-Westerly.pdf">The effective pressure law for the permeability of Westerly Granite under cyclic loading</a>, Journal of Geophysical Research, 91(B3), 3870-3876, 1986.</li>
  <li class="permeability fault">Morrow, C.A., <a href="/static/lfs/research/rockphysics/Nojima_text_Morrow.pdf">Permeability of Deep Drillhole Core Samples</a>, Proceedings, International Workshop on the Nojima Fault Core and Borehole Data Analysis, Nov. 22-23, 1999, Tsukuba, Japan, edited by H. Ito, K. Fujimoto, H. Tanaka and D. Lockner, 2000.</li>
  <li class="strong">Morrow, C.A., and Byerlee, J.D. , <a href="/static/lfs/research/rockphysics/a-note-on-the-frictional-strength-of-laumontite.pdf">A Note on the Frictional Strength of Laumontite from Cajon Pass, California</a>, Geophysical Research Letters, 18(2), 211-214, 1991.</li>
  <li class="strong">Morrow, C.A., and Lockner, D.A., <a href="http://geopubs.wr.usgs.gov/open-file/of01-421/">Hayward Fault Rocks: Porosity, Density and Strength Measurements</a>, U.S. Geological Survey Open-File Report 01-421, 2001.</li>
  <li class="permeability">Morrow, C.A., and Lockner, D.A. , <a href="/static/lfs/research/rockphysics/perm-and-porosity-of-Illinois-UPH-3-drillhole.pdf">Permeability and porosity of the Illinois UPH 3 drillhole granite and a comparison with other deep drillhole rocks</a>, Journal of Geophysical Research, 102(B2), 3067-3075, 1997.</li>
  <li class="permeability">Morrow, C.A., and Lockner, D.A. , <a href="/static/lfs/research/rockphysics/permeability-differences-between-surface-derived.pdf">Permeability differences between surface-derived and deep drillhole core samples</a>, Geophy. Res. Let., 21(19), 2151-2154, 1994.</li>
  <li class="strong">Morrow, C.A., and Lockner, D.A., <a href="https://pubs.usgs.gov/of/2006/1230/">Physical properties of two core samples from well 34-9RD2 at the Coso Geothermal Field, California</a>, U.S. Geological Survey Open-File Report 2006-1230, 2006.</li>
  <li class="permeability fault">Morrow, C.A., Lockner, D.A., Moore, D.E., and Hickman, S.H., <a href="/static/lfs/research/rockphysics/Morrow-AGU-2011.pdf">Permeability, electrical resistivity and frictional strength of SAFOD fault gouge and damage zone rocks</a>, EOS, Tran. Am. Geophy. Un., Fall Meeting (poster), 2011.</li>
  <li class="permeability">Morrow, C.A., Moore, D.E. and Lockner, D.A., <a href="/static/lfs/research/rockphysics/Morrow-etal-JGR-2001-Permeability-reduction-in-granite.pdf">Permeability reduction in granite under hydrothermal conditions</a>, J. Geophys. Res., 106(B12), 30,551-530,560, doi:10.1029/2000JB000010, 2001.</li>
  <li class="permeability">Morrow, C.A., Moore, D.E., and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/perm-and-pore-fluid-chemistry-topopah-springs.pdf">Permeability and pore fluid chemistry of the Topopah Spring Member of the Paintbrush Tuff, Nevada Test Site, in a temperature gradient - Application to nuclear waste storage</a>, Materials Research Society Symposium Proceedings, 26, 883-890, 1984.</li>
  <li class="strong fault">Morrow, C.A., Moore, D.E., and Lockner, D.A., <a href="https://pubs.usgs.gov/of/2010/1184/of2010-1184.pdf">Dependence of frictional strength on compositional variations of Hayward Fault rock gouges</a>, U.S. Geological Survey Open-File Report, 2010-1184, 2010.</li>
  <li class="weak">Morrow, C.A., Moore, D.E., and Lockner, D.A., <a href="/static/lfs/research/rockphysics/mineral_bond_strength.pdf">The effect of mineral bond strength and adsorbed water on fault gouge frictional strength</a>, Geophy. Res. Lett., 27, no. 6, 815-818, 2000.</li>
  <li class="weak">Morrow, C.A., Radney, B., and Byerlee, J., <a href="/static/lfs/research/rockphysics/Frictional_strength.pdf">Frictional strength and the effective pressure law of montmorillonite and illite clays</a>, Fault Mechanics and Transport Properties of Rocks, Academic Press, Ltd, 1992.</li>
  <li class="weak permeability">Morrow, C.A., Shi, L.Q., and Byerlee, J.D. , <a href="/static/lfs/research/rockphysics/permeability-and-strength-of-san-andreas-fault.pdf">Permeability and strength of San Andreas fault gouge</a>, Geophysical Research Letters, 8(4), 325-328, 1981.</li>
  <li class="permeability">Morrow, C.A., Shi, L.Q., and Byerlee, J.D. , <a href="/static/lfs/research/rockphysics/permeability-of-fault-gouge-under-confining-press.pdf">Permeability of fault gouge under confining pressure and shear stress</a>, Journal of Geophysical Research, 89(B5), 3193-3200, 1984.</li>
  <li class="weak">Morrow, C.A., Shi, L.Q., and Byerlee, J.D. , <a href="/static/lfs/research/rockphysics/strainhardening-and-strength-of-clay-rich-fault.pdf">Strain hardening and strength of clay-rich fault gouges</a>, Journal of Geophysical Research, 87(B8), 6771-6780, 1982.</li>
  <li class="weak fault">Morrow, C.A., Solum, J., Tembe, S., Lockner, D., and Wong, T.-f., <a href="/static/lfs/research/rockphysics/2007GL029665.pdf">Using drill cutting separates to estimate the strength of narrow shear zones at SAFOD</a>, Geophy. Res. Lett., 34, L11301, doi:10.1029/2007GL029665, 2007.</li>
  <li class="physics strong"><a name="N" id="N"></a>Nagata, K., Kilgore, B., Beeler, N., and Nakatani, M., <a href="http://onlinelibrary.wiley.com/store/10.1002/2014JB011014/asset/jgrb50712.pdf?v=1&t=hxz50cve&s=c10af3187ce04bbcc57dfd36d5fbd85567d1bdba">High-frequency imaging of elastic contrast and contact area with implications for naturally observed changes in fault properties</a>, JGR     DOI: 10.1002/2014JB011014, 2014.</li>
  <li class="acoustic"><a name="P" id="P"></a>Ponomarev, A., Lockner, D., Stroganova, S., Stanchits, S., and Smirnov, V., <a href="/static/lfs/research/rockphysics/Ponomarev-Oscillating-Load-2010.pdf">Oscillating load-induced acoustic emission in laboratory experiment, in: de Rubeis, V., et al. (eds.), Synchronization and Triggering: from Fracture to Earthquake Processes</a>, GeoPlanet: Earth and Planetary Sciences 1, DOI 10.1007/978-3-642-12300-9_9, Springer-Verlag, Berlin, 2010.</li>
  <li class="weak"><a name="S" id="S"></a>Saffer, D., Lockner, D., and McKiernan, A., <a href="/static/lfs/research/rockphysics/Saffer-Smectite-illite-transform-2012GL051761.pdf">Effects of smectite to illite transformation on the frictional strength and sliding stability of intact marine mudstones</a>, Geophy. Res., Lett., 39, L11304, 2012.</li>
  <li class="strong">Savage, J., Lockner, D., and Byerlee, J., <a href="/static/lfs/research/rockphysics/Savage-Failure-laboratory-fault-models-JGR1996.pdf">Failure in laboratory fault models in triaxial tests</a>, J. Geohy. Res., 101, 22215-22224, 1996.</li>
  <li class="strong fault">Scott, David R., Lockner, D.A., Byerlee, J D., and Sammis, C.G., <a href="/static/lfs/research/rockphysics/Scott1994.pdf">Triaxial Testing of Lopez Fault Gouge at 150 MPa Mean Effective Stress</a>, PAGEOPH, Vol. 142, No. 3/4, 1994.</li>
  <li class="fault">Solum, J.G., Hickman, S.H., Lockner, DA., Moore, D.E., van der Pluijm, B.A., Schleicher, A.M., and Evans, J.P., <a href="/static/lfs/research/rockphysics/Solum2006.pdf">Mineralogical characterization of protolith and fault rocks from the SAFOD main hole</a>, Geophy. Res. Lett., 33, L21314, 2006.</li>
  <li class="permeability">Stanchits, S.A., D.A. Lockner, and Ponomarev, A.V., <a href="/static/lfs/research/rockphysics/AE44.pdf">Anisotropic changes in P-wave velocity and attenuation during deformation and fluid infiltration of granite</a>, Bull. Seis. Soc. Amer., 93 (4), 1803-1822, 2003.</li>
  <li class="strong">Summers, R., and Byerlee, J., <a href="/static/lfs/research/rockphysics/Summary_of_Results.pdf">Summary of results of frictional sliding studies at confining pressures up to 6.98 kb in selected rock materials</a>, U.S. Geological Survey Open-File Report 77-142, 129 pp., 1977.</li>
  <li class="weak fault"><a name="T" id="T"></a>Tembe, S., D. Lockner, and T.-f. Wong, <a href="/static/lfs/research/rockphysics/Tembe-Constraints-on-the-state-of-stress.pdf">Constraints on the stress state of the San Andreas fault with analysis based on core and cuttings from San Andreas Observatory at Depth (SAFOD) drilling phases I and II</a>, J. Geophys. Res., 114, B11401, doi: 10.1029/2008JB005883, 2010.</li>
  <li class="weak fault">Tembe, S., D. Lockner, and T.-f. Wong, <a href="/static/lfs/research/rockphysics/Tembe-Correction-to-Constraints.pdf">Correction to "Constraints on the stress state of the San Andreas fault with analysis based on core and cuttings from San Andreas Observatory at Depth (SAFOD) drilling phases I and II"</a>, J. Geophys. Res., 115, B03418, doi: 10.1029/2009JB000818, 2009.</li>
  <li class="weak">Tembe, S., D.A. Lockner, and T.-f. Wong, <a href="/static/lfs/research/rockphysics/Tembe-Effect-of-clay-content.pdf">Effect of clay content and mineralogy on frictional sliding behavior of simulated gouges: Binary and ternary mixtures of quartz, illite and montmorillonite</a>, J. Geophys. Res., 115, B03416, doi: 10.1029/2009JB006383, 2010.</li>
  <li class="weak fault">Tembe, S., Lockner, D.A., Solum, J.G., Morrow, C.A., Wong, T.-f., and Moore, D.E., <a href="/static/lfs/research/rockphysics/Tembe2006.pdf">Frictional strength of cuttings and core from SAFOD drillhole phases 1 and 2</a>, Geophy. Res. Lett., 33, L23307, doi:10.1029/2006GL027626, 2006.</li>
  <li class="fracture acoustic">Thompson, B., Young, R., and Lockner, D., <a href="/static/lfs/research/rockphysics/ThompsonAE2008JB005753.pdf">Premonitory acoustic emission and stick-slip in natural and smooth-faulted Westerly granite</a>, J. Geophy. Res., 114,B02205, 2009.</li>
  <li class="permeability"><a name="V" id="V"></a>Vaughan, P.J., Moore, D.E., Morrow, C.A., and Byerlee, J.D. , <a href="/static/lfs/research/rockphysics/role-of-cracks-in-progressive-permeability-reduct.pdf">The role of cracks in progressive permeability reduction during flow of heated aqueous fluids through granite</a>, Journal of Geophysical Research, 91(B7), 7517-7530, 1986.</li>
  <li class="permeability">Vernik, L., Hickman, S., Lockner, D., and Rusanov, M., <a href="/static/lfs/research/rockphysics/Vernik-etal-JGR-1994-Ultrasonic-velocities-from-Kola.pdf">Ultrasonic velocities in cores from the Kola superdeep well and the nature of subhorizontal seismic reflections</a>, J. Geophys. Res., 99(B12), 24,209-224,219, doi:10.1029/94JB01236, 1994.</li>
  <li class="fracture">Vernik, L., Lockner, D.A., and Zoback, M.D., <a href="/static/lfs/research/rockphysics/Vernik_SciDrilling1992_Anisotropic-strength-copy.pdf">Anisotropic strength of some typical metamorphic rocks from the KTB pilot hole, Germany</a>, Scientific Drilling, 3, 153-160, 1992.</li>
  <li class="strong acoustic"><a name="W" id="W"></a>Weeks, J. D., D. A. Lockner, and Byerlee, J.D., <a href="/static/lfs/research/rockphysics/Weeks_bval_BSSA78.pdf">Changes in b-value during movement on cut surfaces in granite</a>, Bull. of the Seismological Society of Amer., 68, 333-341, 1978.</li>
</ul>

<!-- Code for filtering reference list by topic

$topics_hash = array(
	'strong' => 'Friction - strong materials',
	'weak' => 'Friction - weak materials',
	'fracture' => 'Fracture and creep',
	'acoustic' => 'Acoustic emission',
	'permeability' => 'Permeability, resistivity, poroelasticity and wave speed',
	'physics' => 'Earthquake physics, modeling, and theory',
	'fault' => 'Fault zone studies'
);


$alpha = array('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');
$letters = array();
$nav_alpha_html = '';
$ref_list_html = '';
$letter_now = '';


// Build Ref list HTML
while ($row_rsRefs = mysql_fetch_assoc($rsRefs)) {
  $ref = new Ref($row_rsRefs['topics'], $row_rsRefs['author'], $row_rsRefs['title'], $row_rsRefs['publication'], $row_rsRefs['year'], $row_rsRefs['attachment'], $row_rsRefs['url']);
  $first_letter = ucwords(substr($ref->author,0,1));
  array_push($letters, $first_letter);
  $letter_prev = $letter_now;
  $letter_now = $first_letter;

  $anchor = '';
  $link = '';
  $publication = '';
  $year = '';

  if ($ref->attachment) $link = 'papers/' . $ref->attachment;
  if ($ref->url) $link = $ref->url;
  if ($link) {
    $title = sprintf ('<a href="%s">%s</a>', $link, $ref->title);
  } else {
    $title = $ref->title;
  }
  if ($ref->publication) $publication = sprintf (', %s', $ref->publication);
  if ($ref->year) $year = sprintf (', %s', $ref->year);

  if ($letter_now != $letter_prev) $anchor = sprintf('<a name="%s" id="%s"></a>', $first_letter, $first_letter);
  $ref_list_html .= sprintf('    <li class="%s">%s%s, %s%s%s.</li>' . "\n", $ref->css_classes, $anchor, $ref->author, $title, $publication, $year);
}

// Build topic filter links HTML
$topics_html = '<ul class="topics">';
$topics_html .= '<li><a href="#" class="sel">All publications</a></li>';
foreach($topics_hash as $key=>$value) {
	$topics_html .= sprintf('<li><a href="#%s">%s</a></li>', $key, $value);
}
$topics_html .= '</ul>';

// Build jump list HTML
$unique_letters = array_unique($letters, SORT_STRING); // Get unique letters in ref list
$unique_letters = array_flip($unique_letters); // Flip key / value so we can test on letter as key

foreach($alpha as $letter) {
  if (isset($unique_letters[$letter])) {
    $nav_alpha_html .= sprintf ('<a href="#%s">%s</a> | ', $letter, $letter);
  } else {
    $nav_alpha_html .= "$letter | ";
  }
}
$nav_alpha_html = sprintf('<div id="nav-alpha">%s</div>', substr($nav_alpha_html,0,-2)); // remove final '|' character after 'Z'

//print "$nav_alpha_html";

?>

<h2>All Publications</h2>
<?php print $topics_html; ?>
    <ul class="referencelist">
<?php print $ref_list_html; ?>
    </ul>

-->
