<?php
// Author: Lisa Wald
// Contact: Nick Beeler
if (!isset($TEMPLATE)) {
  $TITLE = 'Rock Physics Labs - Current Projects';
  $NAVIGATION = true;
  // Use Earthquake level nav file
  include_once 'functions.inc.php';
  ob_start();
  include '_navigation.current.inc.php';
  $NAVIGATION = ob_get_clean();

  include 'template.inc.php';
}
?>

<h2>Earthquake Simulation in High-Velocity Rotary Shear Experiments</h2>

<figure class='right'>
	<video src="/sitedata/research/eqproc/rockphysics/rotary.mp4" width="384" height="310" class="flash" controls></video>
</figure>

<p>
  The <a href="http://earthquakes.ou.edu/reches/Roga/">ROGA (ROtary Gouge Apparatus) test apparatus</a> in the Department of Geophysics at the University of Oklahoma, in Norman, OK was developed by Ze&rsquo;ev Reches at the University of Oklahoma in collaboration with David Lockner at the USGS Earthquake Science Center.  In the accompanying video, a 4 cm diameter rock ring made of gabbro is spun against another gabbro block at about 1 meter-per-second. This is similar to the speed that fault surfaces move past each other during large earthquakes. The rock surfaces are pressed together in the test machine to simulate the high pressure that forces fault surfaces together in the earth. During the experiment, heat is generated by friction as the two rocks rub against each other. Frictional heating can lead to a sudden loss of rock strength during an earthquake, and is an important element in many earthquake models.
</p>

<figure>
  <img src="images/rotary.jpg" width="784" alt="photo and schematic of the ROGA test apparatus" />
</figure>
