<?php
  // Author: Lisa Wald
  // Contact: Elizabeth Cochran
  if (!isset($TEMPLATE)) {
    $TITLE = 'Earthquake Early Warning';
    $NAVIGATION = true;
    // Use Earthquake level nav file
    include_once 'functions.inc.php';
    ob_start();
    include '../_navigation.inc.php';
    $NAVIGATION = ob_get_clean();

    include 'template.inc.php';
  }
?>

<p>
  Earthquake early warning (EEW) systems use earthquake science and the technology of monitoring systems to alert devices and people when shaking waves generated by an earthquake are expected to arrive at their location. The seconds to tens of seconds of advance warning can allow people and systems to take actions to protect life and property from destructive shaking.
</p>

<div class="row">

  <section class="one-of-three column">
    <ul class="no-style linklist">
      <li>
        <a href="overview.php">
          <h4>Overview</h4>
          <img src="images/overview_sm.gif" class='feeds-list-image'
              alt=" icon"  width="75"/>
        </a>
        <p>
          EEW systems are currently operating in several countries, and others are building them. Since 2006 the USGS has been working to develop EEW for the United States, with the help of several cooperating organizations.
        </p>
      </li>
    </ul>
  </section>
  <section class="one-of-three column">
    <ul class="no-style linklist">
      <li>
        <a href="background.php">
          <h4>Background - Early Warning Around the World</h4>
          <img src="images/background_sm.jpg" class='feeds-list-image'
              alt="icon"  width="75"/>
        </a>
        <p>
          Strong seismic shaking from an earthquake travels at about 2 miles per second, so it is possible to detect a large earthquake near its source and broadcast a warning of imminent strong shaking to more distant areas before the shaking arrives.
        </p>
      </li>
    </ul>
  </section>
  <section class="one-of-three column">
    <ul class="no-style linklist">
      <li>
        <a href="currentstatus.php">
          <h4>Current Status</h4>
          <img src="images/current_sm.gif" class='feeds-list-image'
              alt="icon"  width="75"/>
        </a>
        <p>
          A demonstration EEW system called <a href="http://www.shakealert.org/">ShakeAlert&trade;</a> began sending test notifications to selected users in California in January 2012.
        </p>
      </li>
    </ul>
  </section>
</div>

<div class="row">

  <section class="one-of-three column">
    <ul class="no-style linklist">
      <li>
        <a href="nextsteps.php">
          <h4>Next Steps</h4>
          <img src="images/next_sm.jpg" class='feeds-list-image'
              alt=" icon"  width="75"/>
        </a>
        <p>
          Future development of the warning system will include the installation of larger numbers of seismic stations and upgrading station telecommunications.
        </p>
      </li>
    </ul>
  </section>
  <section class="one-of-three column">
    <ul class="no-style linklist">
      <li>
        <a href="news.php">
          <h4>News</h4>
          <img src="images/news_sm.jpg" class='feeds-list-image'
              alt="icon"  width="75"/>
        </a>
        <p>
          Earthquake Early Warning development in the news.
        </p>
      </li>
    </ul>
  </section>
</div>
