<?php

if (!isset($TEMPLATE)) {
  $TITLE = 'Induced Seismicity Ground Motion Workshop';
  $HEAD = '<link rel="stylesheet" href="../index.css" />';
  $FOOT = '<script src="../index.js"></script>';

  include 'template.inc.php';
}

// Initialize variables; set defaults
date_default_timezone_set('America/Los_Angeles');
$datetime = date('Y-m-d H:i:s');
$posting = false;
$workshop_year = 'induced-2017';

if (isSet($_POST['submit'])) { // user submitted form
  $posting = true;

  $fields = array(
    'datetime' => $datetime,
    'fname' => $_POST['fname'],
    'lname' => $_POST['lname'],
    'email' => $_POST['email'],
    'affiliation' => $_POST['affiliation'],
    'postertitle' => $_POST['postertitle'],
    'workshop_year' => $workshop_year
  );

  // Connect to db
  include_once '/etc/puppet/EHPServer.class.php';
  $pdo = EHPServer::getDatabase(
    // the dynamic_earthquake database is replicated between nodes
    'dynamic_earthquake',
    // false = not a read only connection (true is the default)
    false,
    // mysql database ('mysql' is the default, so this is optional)
    'mysql'
  );

  // Insert record
  $stmt = $pdo->prepare('INSERT INTO nca_workshop (datetime, fname, lname,
    email, affiliation, postertitle, workshop_year) VALUES (:datetime,
    :fname, :lname, :email, :affiliation, :postertitle, :workshop_year)'
  );
  try {
    $stmt->execute($fields);
  } catch (Exception $e) {
    print "Error: $e->getMessage()";
  }

  // Create summary html
  $return_html .= '<ul class="no-style results">
      <li><h4>First Name</h4> ' . htmlentities(stripslashes($fields['fname'])) . '</li>
      <li><h4>Last Name</h4> ' . htmlentities(stripslashes($fields['lname'])) . '</li>
      <li><h4>Email</h4> ' . htmlentities(stripslashes($fields['email'])) . '</li>
      <li><h4>Affiliation</h4> ' . htmlentities(stripslashes($fields['affiliation'])) . '</li>
      <li><h4>Poster Title</h4> ' . htmlentities(stripslashes($fields['postertitle'])) . '</li>
    </ul>';

  // Email alert
  $admin = 'abaltay@usgs.gov, shaefner@usgs.gov';
  //$admin = 'shaefner@usgs.gov';
  $headers = "MIME-Version: 1.0" . "\r\n";
  $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
  $headers .= "From: shaefner@usgs.gov";
  $name = htmlentities(stripslashes($fields['fname'])) . ' ' .
    htmlentities(stripslashes($fields['lname']));
  mail($admin, "Workshop form submitted: $name", $return_html, $headers);
}

?>

<h2>February 13&ndash;14, 2017 (Mon&ndash;Tues)</h2>
<p><a href="http://online.wr.usgs.gov/calendar/map.html">Rambo Auditorium, Building 3</a>
  <br />USGS Menlo Park</p>

<?php
  if ($posting) {
    print '<p class="alert success">Thank you for filling out the
    registration form. We&rsquo;ll see you at the workshop.</p>';

    print $return_html;
  }
?>

<div class="row">
  <div class="three-of-five column">
    <p>Understanding the ground motions generated by induced earthquakes in the central US is critical for appropriately modeling these events in hazard maps, and also for understanding the physics that governs them. With the advent of the new 1-year National Seismic Hazard Map updates for induced seismicity in the central US, the USGS has an immediate need to determine the most appropriate ground-motion prediction equation (GMPE) for these induced earthquakes. We also seek to understand the physical controls (primarily stress drop, depth, and crustal structure) on the observed ground motion, to determine if these phenomema are inherently different than natural, tectonic earthquakes.</p>
    <p>The Induced Seismicity Ground Motion Workshop in Menlo Park on February 13-14, 2017 will address both the question of what GMPE should be used in the NSHM as well as understanding the physical controls on the ground motions.</p>
    <p>The workshop will be organized with invited talks that will address data bases of ground motions from induced earthquakes; comparison of existing GMPEs; development of new, hybrid or stochastic GMPEs; physical interpretation of the data and GMPEs; and discussion of the estimation of stress drop of induced earthquakes as a control on the ground motion. The workshop will be organized around these goals, with one outcome being a better idea of what GMPE should be used in the next release of the NSHMs. We also welcome poster contributions that will add to the discussion.</p>

    <h3>Goals</h3>
    <ul>
      <li>Ground-motion modeling guidelines for induced seismicity in the central US. This includes assigning weights to currently available models and developing new empirical, hybrid, or stochastic model.</li>
      <li>Understand the physics behind the magnitude, depth, site, and distance scaling in the observed ground motions and GMPEs.</li>
      <li>Fulfill short-term need of guidance (for hazard maps and ShakeMap) on ground motion model for induced events.</li>
      <li>Coordinate/prioritize ongoing/future efforts between various groups and within the USGS.</li>
    </ul>

    <h3>Logistics</h3>
    <ul>
      <li>Workshop will be held at the USGS Menlo Park on Monday and Tuesday February 13&ndash;14, 2017.</li>
      <li>Hotel room block for federal employees or invited speakers is available at the <a href="http://hotellucent.com">Hotel Lucent in Menlo Park</a> for three nights (Sunday 12th, Monday 13th, Tuesday 14th) at the gov't rate of $199. Please call the Lucent Hotel directly at (650) 521-0024 and ask for USGS room block.</li>
      <li>This hotel is walking distance from the Menlo Park train station, where you can easily arrive from the SFO or SJC airport, as well as the USGS Menlo Park and downtown Menlo Park with many caf&eacute;s and restaurants.</li>
      <li>Invited travelers, please contact the Menlo Park travel desk to arrange your travel.</li>
    </ul>
  </div>
  <div class="two-of-five column">
    <figure>
      <a href="http://www.nasa.gov/images/content/530289main_NRP_map_full.jpg">
        <img src="shakemap.jpg" alt="ShakeMap" />
      </a>
      <figcaption>M 5.8 Pawnee, Oklahoma Earthquake</figcaption>
    </figure>

    <h3>Agenda</h3>
    <p>Check back soon for the agenda.</p>

    <h3>Presentation Guidelines</h3>
    <p>Anyone is welcome to bring a poster; please let us know the title (below). Posters should be no larger than 4&rsquo;x6&rsquo; (AGU size).</p>
    <p>For invited oral presentations, please read <a href="ISGM-workshop-guidelines.pdf">this document</a>.</p>

    <h3>Public Transport</h3>
    <ul class="no-style">
      <li><a href="http://www.caltrain.com/">Caltrain</a></li>
    </ul>
  </div>
</div>

<?php
  if ($posting) {
    return;
  }
?>

<h3>Registration Form</h3>

<p><span class="required">*</span> = Required</p>

<form action="https://earthquake.usgs.gov/contactus/menlo/workshop/induced/"
  name="workshop" id="workshop" method="post" enctype="application/x-www-form-urlencoded">

  <fieldset form="workshop">
    <div class="field">
      <input type="text" id="fname" name="fname" placeholder="Enter first name"
        required maxlength="255">
      <label for="fname">First Name</label>
    </div>
    <div class="field">
      <input type="text" id="lname" name="lname" placeholder="Enter last name"
        required maxlength="255">
      <label for="lname">Last Name</label>
    </div>
    <div class="field">
      <input type="email" id="email" name="email" placeholder="Enter email address"
        required pattern="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A_Za-z]{2,4}$"
        maxlength="255">
      <label for="email">Email</label>
    </div>
    <div class="field">
      <input type="text" id="affiliation" name="affiliation"
        placeholder="Enter affiliation" maxlength="255">
      <label for="affiliation">Affiliation</label>
    </div>
    <div class="field">
      <input type="text" id="postertitle" name="postertitle"
        placeholder="Enter (tentative) poster title" maxlength="255">
      <label for="postertitle">Poster Title</label>
    </div>
  </fieldset>

  <button class="blue" type="submit" id="submit" name="submit">Register</button>

</form>

<p class="privacy"><a href="http://www.usgs.gov/privacy.html">USGS Privacy Policy</a></p>
