<?php
// Author: Lisa Wald
// Contact: Lucy Jones
  if (!isset($TEMPLATE)) {
    $TITLE = 'Earthquake ABC - Parent&apos;s Guide';
    $NAVIGATION = true;
    $HEAD = '<link rel="stylesheet" href="../styles.css"/>';
    include 'template.inc.php';
  }
?>

<div class='row'>
  <div class='column one-of-five'>
    <?php
    include '../jumpmenu.inc.php';
    ?>
  </div>

  <div class='column four-of-five'>
    <img class='dropcap' src="../images/ig.gif" alt="childs drawing of the letter G">
    <h2>as</h2>
    <br style="clear:left;"/>
    <p>
      One of the greatest hazards in earthquakes is that the shaking or ground failure may break gas mains or that appliances or water heaters falling over could break a gas line in a house. Strapping water heaters to the wall to prevent them falling over is a simple and very effective measure to make your own house safer in an earthquake.
    </p>
    <h2>Geology</h2>
    <p>
      The general field of geology includes many specialties involved in the study of the earth. These specialties include geophysics (physics of the earth), geochemistry (chemistry of the earth, both water and rocks) and field geology (the history of the earth through mapping of rock structures). Seismology is one type of geophysics - the study of waves generated by earthquakes as they pass through the earth. Other earthquake scientists include field geologists who map faults in the ground and earthquake engineers who design buildings to withstand earthquakes.
    </p>
  </div>
</div>
