<?php
// Author: Lisa Wald
// Contact: Lucy Jones
  if (!isset($TEMPLATE)) {
    $TITLE = 'Earthquake ABC - Parent&apos;s Guide';
    $NAVIGATION = true;
    $HEAD = '<link rel="stylesheet" href="../styles.css"/>';
    include 'template.inc.php';
  }
?>

<div class='row'>
  <div class='column one-of-five'>
    <?php
    include '../jumpmenu.inc.php';
    ?>
  </div>

  <div class='column four-of-five'>
    <img class='dropcap' src="../images/it.gif" alt="childs drawing of the letter T">
    <h2>hrust</h2>
    <br style="clear:left;"/>
    <p>
      Thrust faults are fault planes where the plane of the fault dips at an angle to the Earth's surface - from a steep dip of 60-70 to almost horizontal - and the rock block on the upper side moves vertically up and over the other side during an earthquake. The Sierra Madre, Elysian Park, Oak Ridge and Torrance-Wilmington are some of  the thrust faults in southern California.
    </p>
    <h2>Time</h2>
    <p>
      The two largest earthquakes to occur in southern California this century occurred between 4 and 5 in the morning. However, the third largest occurred at 10 pm and we have seen large earthquakes at 1 am, 8 am, and 5 pm. Earthquakes can happen at any time and we should plan for them at home, work and school.
    </p>
    <h2>Tsunamis</h2>
    <p>
      When thrust-faulting earthquakes happen under the ocean, the earthquake can push large blocks of ocean floor up. When the ocean floor moves up, the water that was in that spot has to go somewhere else. That somewhere else is into a large wave called a tsunami.
    </p>
    <p>
      Tsunamis can travel across the Pacific. Tsunamis generated by earthquakes in Chile have killed people in Japan. Very few of the offshore faults in southern California are thrust faults so while tsunamis are theoretically possible here, they are very rare.
    </p>
  </div>
</div>
